### ISSUE TITLE
Size limit of results on Profile Directory component not working

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4742] opened 2020-06-04 17:55 UTC
**Describe the bug**

Size limit on number of results for the profile directory component on wagtail isn't getting properly communicated to the pulse api server. 

**To Reproduce**
1. Go to edit 'https://ia-refresh.mofostaging.net/en/what-we-fund/directory/'
2. Try to adjust the profile directory component's 'max number of results', for example set it to '6'
3. Publish or save draft, view live or preview

**Expected behavior**
See more than '6' results displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/20977376/83793416-81a46400-a66a-11ea-87f4-61978fc11fef.png)
![image](https://user-images.githubusercontent.com/20977376/83793497-9f71c900-a66a-11ea-8710-26532fb6cf3d.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.5 
 - Browser: Firefox Nightly
 - Version: 79.0a1

**Comment by Pomax** [comment] 2020-06-30 18:51
Reviewing the code and history of this component, this was by design: the directory component was created specifically to show all our pulse-registered fellows, separated only on year. We implemented it as "a type of `profile list`" so it inherited that component's size field, but we seem to have forgotten to blank that out on the admin side: the code goes out of its way to ensure that there is _no_ limit applied for the directory list.

@kristinashu @beccaklam if we want to change this, we should probably reevaluate whether this component is the right one for what the above-mentioned page wants to surface (it might be more appropriate to instead use the profile listing component), and if it is, whether it needs to be rewritten in order to show the full year-indexed fellows listings but limited to a specific initial number, with a "show more" or "show all" button.

**Comment by Pomax** [comment] 2020-06-30 18:52
(removing issue estimate pending figuring out what the work requirements would be)

**Comment by beccaklam** [comment] 2020-07-02 19:09
I think for this design we can get away with using the profile listing component @Pomax cc: @kristinashu 

I wasn't aware of that particular component before but saw it used on the Fellowship's 'Meet the Team' page and it does the job for this design.

This ticket should be good to close then?

**Comment by kristinashu** [comment] 2020-07-02 20:37
Ideally it would show as Pomax suggested 
> rewritten in order to show the full year-indexed fellows listings but limited to a specific initial number, with a "show more" or "show all" button"

But since the future of Pulse is currently being assets, I think we can close this ticket for now and reassess all the Pulse components once we know more. 

@Pomax I leave it to you to close if you agree!

**Comment by Pomax** [comment] 2020-07-02 21:36
If the profile listing component gets the job done, then yes: let's close this one for now, and then we can revisit the directory component if and when we decide we want it to do more than it currently does. 

Thanks!

**Closed by Pomax** 2020-07-02 21:36 UTC
Labels: bug, engineering
