### ISSUE TITLE
Investigate why unexpected changes occurred on mozfest site  

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8132] opened 2022-01-21 17:07 UTC
@marcwalsh filed these two tickets https://github.com/mozilla/foundation.mozilla.org/issues/8020 & https://github.com/mozilla/foundation.mozilla.org/issues/8131 which reflect changes that happened unintentionally.

Investigate why these changes happened and how to avoid this they of issue in the future.

Note from @Pomax via slack:

> nothing immediately comes to mind, we haven't done any mozfest related work, but let's check to make sure mozfest pages are covered by visual regression checks too.

**Comment by tbrlpld** [comment] 2022-02-08 19:56
@kristinashu @marcwalsh I have been looking into this a bit now and here are my findings. 

First, both issues are MozFest styling related, but otherwise appear unrelated. 

# Progress bars

There is one large commit as part of  #7603 that added the changes that seem to have caused the issue: https://github.com/mozilla/foundation.mozilla.org/commit/b5e42ed1edcb012f3ce0cf92bb45d3aa6aaeb839#diff-a3ba203a3bd2eb770b069de5e4ab5bd73270b8b9c0d8995148969bd5eff4717eR305

This is a squash commit adding bunch of work around the “community directory”. Committed on 15 Dec 2021. The contained commits go back till October 2021. So quite the big merge.

My assumption is that the merge broke the progress bars, but that it was just not noticed in the week before Christmas (potentially due to low staffing etc.). 

# Current event sliders

Originally added in 4 Nov 2021: #7457

No other changes to this file outside of the original creation and now the fix. 

The bug was caused by the purging mechanism which can not recognise class names when they are touching other symbols (e.g. curly braces `{`) that are used in the Django template language, but do not typically touch class names in plain HTML. Because the purge pattern is not aware that these are special symbols, it recognizes them as part of the class names and therefore will purge the class name that we actually wanted. 

Now, why did this not happen before? Potentially, the same class was used elsewhere in the code base (where it did not touch any special character) and was therefore not purged. This mean in the final CSS the class was present and worked as intended. (I tried to find such uses but could not find any). 

Also, Tailwind has been updated in the meantime, from 2.2.9 to 3.0.12. I don’t see any explicit notice in the changelog regarding the purge behaviour (https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md#300---2021-12-09). Maybe this happened as part of the switch to the JIT compiler.

**Comment by kristinashu** [comment] 2022-02-11 01:05
Thank you for looking into this @tbrlpld. Do you know if regression checks would have caught this? Do we have this set up for the mozfest site? Just wondering how we can avoid these types of unexpected changes in the future.

**Comment by tbrlpld** [comment] 2022-02-15 15:09
@kristinashu Yea, this looks like a good case for the visual tests in Percy. I think the visual regression test should have detected both of them since in each case the rendered result was affected. 

I am not sure how the tests can be set up though. Maybe @danielfmiranda, @Pomax or @fessehaye can help?

**Comment by tbrlpld** [comment] 2022-02-18 20:26
@Pomax The docs are saying that the visual regression tests are defined in Cypress: https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#visual-regression-testing

Am I misunderstanding something here?

**Comment by tbrlpld** [comment] 2022-02-18 20:27
I also notices we are already testing the Mozfest homepage. But, the Mozfest homepage on `main` does not seem to look quite right. Maybe the fake data needs to be updated.

**Comment by tbrlpld** [comment] 2022-02-18 20:43
Now I see the REAME mentioning Percy and Playwright 😅 https://github.com/mozilla/foundation.mozilla.org#visual-regression-tests

This might need some straightening.

**Closed** 2022-02-23 00:26 UTC
Labels: engineering, mozfest

**Comment by kristinashu** [comment] 2022-02-23 16:25
Awesome, thank you Tibor!
