### ISSUE TITLE
Fake data generation still triggers (legitimate) Percy errors

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2786] opened 2019-03-11 20:22 UTC
[This Percy run](https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/1546527) highlights the issue- this isn't a real visual regression. Something about our approach to generating data for review apps needs attention.

**Comment by Pomax** [comment] 2019-03-13 22:40
we bootstrap based on a random seed, and we do not reset that seed at any point during the load_fake_data run, so any time random generated data changes, it's usually because something about the actual data itself changed, such as: a new model field, the removal of a model field, a new model entirely, the removal of an entire modal, a new streamfield block, the removal of a streamfield block, etc.

Anything that might change the data that _can_ get generated _will_ change the data that gets generated.

**Comment by alanmoo** [comment] 2019-05-13 15:12
Let's use this to have a conversation about our fake data generation in general. Is it still useful? What are we trying to do with it? Are we better served by another approach, like cloning the staging database to review apps, possibly having a directory of components pre-built for visual regression/functional testing?

**Comment by cadecairos** [comment] 2019-06-07 17:52
If we want to minimize the visual changes we're experiencing, we will want to consider using fixtures for pages that we want to test on Percy. This will mean we'll be on the hook for updating them when something changes. I still think there's a valid use for generation of model instances using faker+factory boy, but it's certainly not a good solution for pages we're testing for vidual regressions.

**Comment by Pomax** [comment] 2019-07-09 21:20
@alanmoo this feels like it falls into the "figuring out what data we want for testing" bucket: do we want to stick with the fake data approach we're using now, or do we want specific real pages that we made of the past few months as representative pages for whatever we're trying to test against?

**Comment by alanmoo** [comment] 2019-07-10 16:29
For Percy, my instinct is that we should be using a clone of the production database.  @patjouk and I had a conversation around this the other week, and I believe we netted out on "let's see what stumbling blocks we come across in the upcoming weeks and document them, then figure out what approach we should take.

**Comment by alanmoo** [comment] 2019-11-08 21:16
Has anyone had more thoughts/experience on this?

**Comment by mmmavis** [comment] 2019-12-05 20:31
This is happening in my PR https://github.com/mozilla/foundation.mozilla.org/pull/4019.

Percy snapshot that's flagging error: https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/3384277/view/208378693/1280?mode=diff&browser=chrome&snapshot=208378693

**Comment by cadecairos** [comment] 2020-02-25 22:10
@Pomax didn't you say recently that Percy updated Chrome which fixed a style bug? Do we know if this is a problem still (or is this unrelated to that?)

**Comment by cadecairos** [comment] 2020-02-27 18:46
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.

**Closed by cadecairos** 2020-02-27 18:46 UTC
Labels: bug, engineering, needs discussion, testing
