### ISSUE TITLE
MozFest: Ticket Widget

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#3121] opened 2019-05-08 23:47 UTC
### Description
For Mozilla Festival 2019, a main call to action for the site will be for ticket sales.

**Tickets Page**
We have previously embedded buttons from [ti.to's embeddable widgets](https://ti.to/docs/widget). We did not modify the lightbox it launches as I don't think it allowed for customization either? It looked something like this:
![image](https://user-images.githubusercontent.com/2492510/57415270-71dcf680-71b0-11e9-84d0-572dc6c3f6f6.png)
Will we be using the same button system and can we embed them our cms subpages?

Wireframe on redpen here: https://redpen.io/vy1d8f50e4c69ff620
<img width="886" alt="image" src="https://user-images.githubusercontent.com/2492510/57415349-ae105700-71b0-11e9-86b5-7d3490a13db5.png">

**Comment by sabrinang** [comment] 2019-05-09 20:22
Note: a fallback can be a button with an external link to a tito page with all our ticket options

**Comment by mmmavis** [comment] 2019-05-09 20:23
Example of a [tito ticket page](https://ti.to/Mozilla/mozfest-2017) from MozFest 2017.

**Comment by beccaklam** [comment] 2019-05-13 18:51
Alan commented more in depth on this issue in this ticket: https://github.com/MozillaFoundation/mozfest-website-2019/issues/8. Looks like the dev team needs to scope it out?

**Comment by mmmavis** [comment] 2019-05-13 19:23
Code example from last year if we decide to embed a tito button to launch the Tito lightbox: 
https://github.com/mozilla/mozillafestival.org/blob/master/pages/tickets.jsx#L166-L169

**Comment by alanmoo** [comment] 2019-05-14 13:10
@beccaklam that was before we had the kickoff meeting planned. Sabrina’s most recent comment reflects that call.

**Comment by gideonthomas** [comment] 2019-05-14 22:50
@alanmoo I think we should scrap this and prioritize other enhancements to the MozFest site. Making a decision now would help design move forward.

**Comment by gideonthomas** [comment] 2019-05-15 18:06
Actually, let's keep this ticket since it's a preferable option for the OLE team. However, we need an acceptable version for June. Chatting in Slack and will update here

**Comment by kristinashu** [comment] 2019-05-22 17:41
@gideonthomas to confirm that we can link out to the individual tickets, if that's the case then there is no dev work to be done here.

**Comment by kristinashu** [comment] 2019-05-22 23:14
@mmmavis confirmed we can link directly to a ticket so closing this!

**Closed by kristinashu** 2019-05-22 23:14 UTC
Labels: engineering
