### ISSUE TITLE
Nav Update: Multipage campaigns with long page titles look...weird

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1660] opened 2018-07-09 16:29 UTC
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1682681/42463235-862fabae-8373-11e8-8928-0476f0174884.png">

Not a huge issue since we can say "don't do that" for now, but it should fail gracefully. @kristinashu Assigning to you to identify a design solution (or assign someone else who can provide one) After that's done, flip it back to me for dev assignment.

**Comment by gvn** [comment] 2018-07-09 16:31
Live text gonna live text. 

A design solution / implementation should accommodate multiple lines.

**Comment by kristinashu** [comment] 2018-08-03 16:51
I put this at a low priority since right now this nav is only on the Aadhaar page, which has short nav names.

But the backup can be like this: 
- More vertical space between the two lines of text
- Light grey line below both lines of text and extending the full width
- If possible, don't breakup a nav name (i.e. in Alan's example, "Think arm serious evidence everybody pretty condition" should be on one line).

<img width="690" alt="image" src="https://user-images.githubusercontent.com/1068783/43655032-3c895f34-9702-11e8-921d-5e3009af9050.png">

**Comment by youriwims** [comment] 2019-01-10 17:51
Thanks, will do!

**Comment by Pomax** [comment] 2019-01-10 20:12
As far as I know this is only really a problem in development with autogenerated Faker text (which doesn't stick to using short titles for campaign pages, and so creates _really bad looking menu headings_ =D). It's totally worth fixing the spacing, but I would say let's not try to make thing fit over multiple lines right now, especially as there's nothing on the live site that runs into this problem.

And maybe it's worth filing a follow-up issue here around fixing the Faker text for campaigns so that it generates more sensible text for this type of page /cc @alanmoo @cadecairos

**Comment by youriwims** [comment] 2019-01-11 16:01
@Pomax the spacing and gray line is only an issue when the nav wraps. The nav's parent container has a margin-bottom so, vertical spacing will be okay if it's only one line. Like we talked about yesterday, I can always add a Flex gutter to increase vertical spacing if the nav wraps at the very least.

@kristinashu I'm able to improve the vertical spacing between multiple lines of the nav in the event it wraps. However, I'm unable to keep the gray line consistent on each line if wrapping does occur. Let me know how you would like me to move forward.

This solution to this issue seems to be dependent upon whether or not there will be rules applied to this type of nav detailing max words/characters per li (@Pomax ) in addition to potential nav wrapping design(@kristinashu ). Please keep me updated on what you both decide :)

**Comment by youriwims** [comment] 2019-01-11 19:00
This is similar to how it would appear. Currently, if we add the vertical spacing in case the nav wraps, it would technically be a margin-bottom that adds the "gutter"/spacing. This is how it would look: 
![screen shot 2019-01-11 at 1 52 49 pm](https://user-images.githubusercontent.com/36484608/51053649-389ccd00-15a8-11e9-9e61-2694893cd9c5.png)
Unfortunately, whatever margin-bottom is on the top row items will also be on the bottom as well which is the cause for the large spacing below the second line of items. Below is what it would look like with the nav wrap spacing and decreased padding-bottom/spacing between the nav text & underline: 
Top & Bottom links hover
![screen shot 2019-01-11 at 1 56 51 pm](https://user-images.githubusercontent.com/36484608/51053886-fd4ece00-15a8-11e9-9a87-eeedfa75aada.png)
Top Link hover
![screen shot 2019-01-11 at 1 57 20 pm](https://user-images.githubusercontent.com/36484608/51053887-fd4ece00-15a8-11e9-9460-499971c2dc0d.png)

Let me know what you think is best.

**Comment by kristinashu** [comment] 2019-01-11 20:09
Ok, feel free to reduce the padding! Just make sure that the light gray line lines up with the black underline like so:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/1068783/51057121-83fbaf00-1599-11e9-952e-174cd511cb3a.png">

**Comment by mmmavis** [comment] 2019-01-11 20:17
@kristinashu since I'm pretty involved with the nav cleanup work...

Question: is this change just for multipage links on the **campaign** pages? Or any pages on Foundation site that have multipage links (e.g., opportunity page, about page, etc)

**Comment by kristinashu** [comment] 2019-01-11 21:13
For now, let's just change it on the multi-page campaigns. 

FYI to Youri: Mavis will eventually be working on turning this sub nav into a template. It will then be used everywhere that we have a horizontal sub nav (example: primary pages like [About Us](https://foundation.mozilla.org/en/about/) and campaign pages like [Aadaar](https://foundation.mozilla.org/en/campaigns/aadhaar/)).

**Comment by mmmavis** [comment] 2019-01-11 21:15
@youriwims do what you need to do to land the fix. Just tag me in the PR so I'm aware of the nav changes you are adding to the codebase 👍

**Comment by youriwims** [comment] 2019-01-11 21:15
Sounds good!

**Comment by youriwims** [comment] 2019-01-11 22:03
@kristinashu, if space is added between the nav wrap, the gray line won't line up with the black underine.

**Comment by kristinashu** [comment] 2019-01-11 22:17
Chatted with Youri and sounds like there is no _elegant_ design solution for this. We think the best way to proceed will be to update faker text and explore options to limit character count and number of nav items. I will open up tickets for these. 

@youriwims if this all sounds right, please close this ticket!

**Comment by youriwims** [comment] 2019-01-11 22:19
Sounds good, thanks @kristinashu :)

**Closed by youriwims** 2019-01-11 22:19 UTC
Labels: bug, engineering, good first issue, quality test
