### ISSUE TITLE
PNI - make sure factory generates fake product images

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5983] opened 2021-01-08 20:08 UTC
Currently, none of the products have fake product image generated.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2896608/104059328-07146780-51aa-11eb-8187-78c5830adb98.png">

**Comment by Pomax** [comment] 2021-01-11 18:38
Hm, I'm pretty sure before I left we landed a PR that generates fake product images, except the images were all "blue rectangles"?

**Comment by Pomax** [comment] 2021-02-02 19:43
origin code for providing real images: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/utility/faker/image_provider.py

**Comment by Pomax** [comment] 2021-03-10 23:47
closing as duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/5905

**Closed by Pomax** 2021-03-10 23:47 UTC
Labels: Buyer's Guide 🛍, engineering
