### ISSUE TITLE
CSP errors

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2727] opened 2019-02-26 21:15 UTC
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1682681/53446779-c0685a80-39e1-11e9-9652-08a6b57fd3ca.png">

**Comment by Pomax** [comment] 2019-02-27 00:14
I can't reproduce this, which OS/browser combination?

**Comment by alanmoo** [comment] 2019-02-27 14:41
Hmm, Firefox 65 Mac OS. Looks like the errors are a browser add-on, but the child-src deprecation sticks around even with all add-ons disabled.

**Comment by cadecairos** [comment] 2019-02-27 16:52
If an addon is injecting inline fonts, you're gonna have a bad time. The child-src deprecation thing is not an issue, it's just Firefox being stupid about the CSP 3 Spec. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1486331
https://github.com/w3c/webappsec-csp/pull/313

**Comment by Pomax** [comment] 2019-02-27 17:53
Add-ons geting blocked is effectively "CSP doing exactly what it should be doing" (even if we vehemently disagree with whether or not the website owner's CSP should get to dictate the user's experience, overruling intentionally installed addons that are _meant_ to inject functionality into the document).

Closing as "does what it's supposed to" =(

**Closed by Pomax** 2019-02-27 17:53 UTC
Labels: DevOps, bug
