### ISSUE TITLE
People Cards: invisible twitter icon 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4520] opened 2020-04-15 23:40 UTC
**Describe the bug**
Twitter icon on people cards not seen until hover state.

**To Reproduce**
1. Go to: 
https://foundation.mozilla.org/en/fellowships/meet-our-fellows/
https://foundation.mozilla.org/en/fellowships/meet-team/

2. Hover over area beside linked in icons.

**Expected behavior**
Should be present and black beside linkedin icon.

**Screenshots**
![missing-twitter](https://user-images.githubusercontent.com/2492510/79398420-86378080-7f35-11ea-9da1-f1ac7e60bffe.gif)

missing gap on mobile (ignore my screen tint):
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2492510/79398896-b2073600-7f36-11ea-900f-80fe5abc0385.png">

**Desktop (please complete the following information):**
 - OS: iOS 10.15.4
 - Browser: Firefox 74.0.1 & Chrome 80.0.3987.163

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: android 10
 - Browse: Firefox 68.7.0 & Chrome 81.0.4044.96

**Comment by mmmavis** [comment] 2020-04-16 22:11
Dupe of #4469. Closing.

**Closed by mmmavis** 2020-04-16 22:11 UTC
Labels: bug
