### ISSUE TITLE
investigate why review apps are installing the wrong version of wagtail

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#1788] opened 2018-08-28 17:20 UTC
We're seeing Heroku installing wagtail 2.2.1 in things like https://foundation-mofostaging-pr-1785.herokuapp.com/cms (click `settings`, and then the wagtail version is listed at the bottom of the expanded menu), despite the fact that both the `Pipfile` and `Pipfile.lock` both indicate that the only permitted version is v2.1.2 (see [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/Pipfile#L27) and [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/Pipfile.lock#L436)).

It looks like that Wagtail v2.2.1 has a bug around XHR processing (instead opening XHR responses as new URLs, it's super weird O_o) so we can't upgrade until we figure out why that happens, and while both staging and production are properly installing v2.1.2, the review apps seem to have started ignoring the strict version instruction recently.

**Comment by patjouk** [comment] 2018-08-29 11:29
I've checked that PR and only saw wagtail 2.1.2 on the admin section. I also verified on Heroku and it's 2.1.2 that's installed. I also checked PR1787 and it's also 2.1.2.
Can you check again and see if you could reproduce this issue? Thanks!

**Comment by Pomax** [comment] 2018-08-29 15:09
Hm, that was not the version we were seeing when the problem arose, time to check if the responses on that review app are no longer JSON.

**Comment by Pomax** [comment] 2018-08-29 15:11
I don't see any weird XHR responses now, hopefully @gvn can confirm they are gone.

**Comment by patjouk** [comment] 2018-08-29 20:08
I can't reproduce the error, but when I try to upload an image on pr1785 or 1787, I get:

```
2018-08-29T19:59:00.076296+00:00 app[web.1]: [2018-08-29 19:58:59,833] [ERROR] Internal Server Error: /cms/images/multiple/add/

2018-08-29T19:59:00.076308+00:00 app[web.1]: Traceback (most recent call last):

2018-08-29T19:59:00.076310+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute

2018-08-29T19:59:00.076311+00:00 app[web.1]:     return self.cursor.execute(sql, params)

2018-08-29T19:59:00.076313+00:00 app[web.1]: psycopg2.IntegrityError: null value in column "file_hash" violates not-null constraint

2018-08-29T19:59:00.076378+00:00 app[web.1]: DETAIL:  Failing row contains (2, IMG_20180723_122536.jpg, original_images/IMG_20180723_122536.jpg, 4640, 3480, 2018-08-29 19:58:59.828646+00, null, null, null, null, 1, 3677587, 1, null).

2018-08-29T19:59:00.076381+00:00 app[web.1]: 

2018-08-29T19:59:00.076383+00:00 app[web.1]: 

2018-08-29T19:59:00.076384+00:00 app[web.1]: The above exception was the direct cause of the following exception:

2018-08-29T19:59:00.076386+00:00 app[web.1]: 

2018-08-29T19:59:00.076387+00:00 app[web.1]: Traceback (most recent call last):

2018-08-29T19:59:00.076389+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner

2018-08-29T19:59:00.076390+00:00 app[web.1]:     response = get_response(request)

2018-08-29T19:59:00.076395+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response

2018-08-29T19:59:00.076397+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)

2018-08-29T19:59:00.076398+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response

2018-08-29T19:59:00.076400+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2018-08-29T19:59:00.076402+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 52, in inner

2018-08-29T19:59:00.076403+00:00 app[web.1]:     return func(*args, **kwds)

2018-08-29T19:59:00.076405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled

2018-08-29T19:59:00.076406+00:00 app[web.1]:     response = viewfunc(request, *args, **kw)

2018-08-29T19:59:00.076408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper

2018-08-29T19:59:00.076410+00:00 app[web.1]:     return view_func(request, *args, **kwargs)

2018-08-29T19:59:00.076411+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view

2018-08-29T19:59:00.076413+00:00 app[web.1]:     return view_func(request, *args, **kwargs)

2018-08-29T19:59:00.076415+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/admin/utils.py", line 145, in wrapped_view_func

2018-08-29T19:59:00.076416+00:00 app[web.1]:     return view_func(request, *args, **kwargs)

2018-08-29T19:59:00.076418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/vary.py", line 21, in inner_func

2018-08-29T19:59:00.076419+00:00 app[web.1]:     response = func(*args, **kwargs)

2018-08-29T19:59:00.076421+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/images/views/multiple.py", line 70, in add

2018-08-29T19:59:00.076423+00:00 app[web.1]:     image.save()

2018-08-29T19:59:00.076424+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save

2018-08-29T19:59:00.076426+00:00 app[web.1]:     force_update=force_update, update_fields=update_fields)

2018-08-29T19:59:00.076427+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base

2018-08-29T19:59:00.076429+00:00 app[web.1]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

2018-08-29T19:59:00.076431+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table

2018-08-29T19:59:00.076432+00:00 app[web.1]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

2018-08-29T19:59:00.076434+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert

2018-08-29T19:59:00.076435+00:00 app[web.1]:     using=using, raw=raw)

2018-08-29T19:59:00.076437+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method

2018-08-29T19:59:00.076438+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)

2018-08-29T19:59:00.076440+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert

2018-08-29T19:59:00.076442+00:00 app[web.1]:     return query.get_compiler(using=using).execute_sql(return_id)

2018-08-29T19:59:00.076443+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql

2018-08-29T19:59:00.076445+00:00 app[web.1]:     cursor.execute(sql, params)

2018-08-29T19:59:00.076446+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute

2018-08-29T19:59:00.076448+00:00 app[web.1]:     return self.cursor.execute(sql, params)

2018-08-29T19:59:00.076449+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__

2018-08-29T19:59:00.076451+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)

2018-08-29T19:59:00.076453+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise

2018-08-29T19:59:00.076455+00:00 app[web.1]:     raise value.with_traceback(tb)

2018-08-29T19:59:00.076456+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute

2018-08-29T19:59:00.076458+00:00 app[web.1]:     return self.cursor.execute(sql, params)

2018-08-29T19:59:00.076459+00:00 app[web.1]: django.db.utils.IntegrityError: null value in column "file_hash" violates not-null constraint

2018-08-29T19:59:00.076469+00:00 app[web.1]: DETAIL:  Failing row contains (2, IMG_20180723_122536.jpg, original_images/IMG_20180723_122536.jpg, 4640, 3480, 2018-08-29 19:58:59.828646+00, null, null, null, null, 1, 3677587, 1, null).

2018-08-29T19:59:00.076471+00:00 app[web.1]: 

2018-08-29T19:59:00.338508+00:00 heroku[router]: at=info method=POST path="/cms/images/multiple/add/" host=foundation-mofostaging-pr-1787.herokuapp.com request_id=ac7bf4b5-5eb1-425a-9231-f59877c155d7 fwd="" dyno=web.1 connect=0ms service=4432ms status=500 bytes=895 protocol=https

2018-08-29T19:59:00.337977+00:00 app[web.1]: 10.181.92.244 - - [29/Aug/2018:19:59:00 +0000] "POST /cms/images/multiple/add/ HTTP/1.1" 500 27 "https://foundation-mofostaging-pr-1787.herokuapp.com/cms/images/multiple/add/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0"

```

To reproduce:
- https://foundation-mofostaging-pr-1785.herokuapp.com/cms/images/multiple/add/
- add an image.

You can check the logs in Heroku. Click on the review app, then the "more" button and "view logs".

**Comment by patjouk** [comment] 2018-08-31 09:34
Whatever happened is now fixed. I deployed review apps with wagtail 2.1.2 and 2.1.3 and Heroku respected both versions.
I'm gonna check again on Monday to see what failed but it will be difficult to investigate if I can't reproduce the issue again. I'm gonna close this issue for now.

**Closed by patjouk** 2018-08-31 09:34 UTC
Labels: DevOps
