### ISSUE TITLE
Add new criteria and remove old criteria - template & styling

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5255] opened 2020-09-16 22:20 UTC
### Add new criteria and remove old criteria

- [x] Add all the criteria to match the [spreadsheet](https://docs.google.com/spreadsheets/d/1cOOzLhkoICFIPTUmxQnrH10HZz1qq5eHF51qgj1p8QM/edit#gid=0)
- [x] Remove criteria that are no longer needed 
- [x] Update the styling to match the [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Like on production, if there is no help text then that section should be hidden
- [x] If the answer to the first AI questions is `No` then the other two questions should be hidden

All styling should use styles that are already on production.

Ding will be added in  - Add "privacy" ding #5308 
Criteria can be ordered - Reorder the criteria in the product template #5253

### Desktop comp

What is required to signup?
<img width="832" alt="image" src="https://user-images.githubusercontent.com/1068783/93530862-22a1ec80-f8f3-11ea-8a77-4b74d7a1bb49.png">

What data does it collect?
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1068783/93531051-77456780-f8f3-11ea-8e4d-2ef5201fd899.png">

How does it use this data?
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1068783/93531067-7d3b4880-f8f3-11ea-8d80-5917ddd4c070.png">

How can you control your data?
<img width="832" alt="image" src="https://user-images.githubusercontent.com/1068783/93531101-862c1a00-f8f3-11ea-9060-3d17eab5d880.png">

What is the company's known track record of protecting user's data?
<img width="833" alt="image" src="https://user-images.githubusercontent.com/1068783/93531116-8debbe80-f8f3-11ea-838d-b9871f671c1e.png">

Can this product be used offline?
<img width="832" alt="image" src="https://user-images.githubusercontent.com/1068783/93531132-93490900-f8f3-11ea-8564-e77c7525739d.png">

Artificial Intelligence section
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1068783/93531153-9ba14400-f8f3-11ea-8a77-c00bbcf15dc3.png">

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - n/a
- [x] Hover state for elements are designed - use existing styles
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by Pomax** [comment] 2020-09-17 16:44
closing as duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/5241

**Comment by Pomax** [comment] 2020-09-17 16:47
unclosing, this was frontend, not backend.

**Comment by mmmavis** [comment] 2020-10-02 23:06
Done. We still need to update the template code so new criteria show up only on "general" product pages. I've filed two new tickets for it.

Closing this one now.

**Closed by mmmavis** 2020-10-02 23:06 UTC
Labels: Buyer's Guide 🛍, engineering, frontend
