### ISSUE TITLE
Anchor links lead to wrong position on MozFest page

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#7069] opened 2021-07-12 19:56 UTC
### Describe the bug
I'm using anchor links to send users to the different year heading on the [On-Demand page](https://www.mozillafestival.org/on-demand/previous-festivals) of the MozFest website. When a user clicks the link they are sent to the wrong position on the page.

### To Reproduce
1. Go to 'https://www.mozillafestival.org/on-demand/previous-festivals#mozfest-2019-healthy-ai'
2. You'll be brought to a point in the page before the MozFest 2019 | Healthy AI heading.

### Expected behavior
The link should position the page to the MozFest 2019 | Healthy AI heading

### Desktop (please complete the following information):
 - OS: MacOS 11.4
 - Browser: Chrome / Safari / FireFox

### Smartphone (please complete the following information):
 - Device: iPhone 12 Pro
 - OS: iOS 14.6
 - Browser: Safari

### Additional context
When watching the page load - it seems to load in the correct position, then the Pulse entries on the page load and push the headings down the page.

**Comment by benhohner** [comment] 2021-07-19 20:47
@marcwalsh I just tried it and I think it works for me, maybe it's fixed? If still broken, can you please add a screenshot?

**Comment by benhohner** [comment] 2021-09-13 17:25
Seems to be fixed. Feel free to reopen if you can reproduce again!

**Comment by marcwalsh** [comment] 2021-09-15 16:26
Hey @benhohner - sorry I missed the comment before. Tried this again in FF and Chrome and the issue is still there. When on the page, and clicking the anchor links at the top of the page. It loads the page at the anchor point, however since the Pulse entries load after the page loading at the anchor point it means that content is then no longer at that position. 

I can send a screen recording if that's useful?

**Comment by Pomax** [comment] 2021-11-24 23:18
Problem analysis:
- URL navigation works
- DOM content gets late-loaded in, changing the scroll position
- this happens fast enough to create a user experience corresponding to being navigated to the wrong place in the document

Possible solutions:
- force fragmentid navigation once the DOM is stable, _and_ less than X seconds have passed

However, this also kind of feels like a browser behaviour bug. If a user opens a page at some fragment id, and does not interact with the page, out-of-view late loading content should keep users looking at what they're looking at, instead of moving them around on the page. Odds of getting that fixed in both Chrome and Firefox in anything even remotely close to a timely manner are, of course, effectively zero

**Comment by danielfmiranda** [comment] 2021-12-03 21:15
After further research I am seeing that this behavior can only be reproduced on Chrome/Safari and not firefox.

For example on FF when I get click on  https://www.mozillafestival.org/en/on-demand/previous-festivals/ both with and without the #mozfest-2019-healthy-ai appended, it appears to render in the correct location even after the content is loaded in:

![image.png](https://images.zenhubusercontent.com/6046b7f1bc36adc9ce95a16a/c9386252-b8de-4b39-af9e-81aa3654030d)

**Comment by danielfmiranda** [comment] 2021-12-03 22:43
After discussing with Simon he brought up that since these items are react components, it could be possible to have a scrollTo function set up so when the component is updated, we take whatever anchor link is in the URL and scroll there. 

I think this sounds like a possible solution, however since we have multiple items on the same page I am curios how the behavior will appear to the user. 

Going to give this a try today/Monday and will keep the team updated!

**Closed** 2021-12-10 00:34 UTC
Labels: bug, engineering, wagtail, frontend
