### ISSUE TITLE
Homepage wireframe update

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4666] opened 2020-05-19 16:20 UTC
Iterate on the homepage to consider 2 new feedback pieces from InVision:

- "Anil has highlighted that we might miss the our current hero space (accessible project with a clear CTA), should we add that back in? I still think it should be below the value prop and TBD titles but maybe above the blog posts."
- Titles check (by content team)

**Comment by taisdesouzalessa** [comment] 2020-05-19 20:59
Here are the options for this ticket. First, a bit of background information:

**Challenge:** how can we balance the needs of new users and returning visitors? For a new visitor to the home page, having a value proposition is very useful to quickly understand what we do and why. For a recurring visitor, seeing the same message again and again can be frustrating (they may want to jump straight into the "fresh" content.

**Analytics:**  during 2020, most visitors to our homepage (/en/ only) are new. We have around 8x more unique page views from new users than from returning ones. Also, more than 70% of them see our homepage from desktop devices. 

**Future:** since we plan to shift our audience targeting, we should consider the site in mobile as well. We may see more people using our page on mobile in the future.

### Proposals:
_____
V3 ([see full page](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418350320_Home_-_Value_Prop_Highlight_V3))

**Comments:**
I like how value prop and the 3 areas are all together on top. They don't take too much space. The issue is on mobile, where returning visitors will have to scroll past this area to see "fresh" content.

**Screenshot:**
<img width="822" alt="image" src="https://user-images.githubusercontent.com/22157921/82376488-0f2f5500-99d7-11ea-835d-0a89eae328b4.png">

_____
V4 ([see full page](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418350318_Home_-__value_Prop_Highlight__V4_))

**Comments:**
I like how this option has a simple value prop on top that is easy to scan. For new users, they can quickly understand what we do (and dive a bit deeper after the highlight). For returning users, they can ignore it and go straight to "fresh" content. It works well in mobile. This is my favorite option.

**Screenshot:**
<img width="829" alt="image" src="https://user-images.githubusercontent.com/22157921/82376517-16eef980-99d7-11ea-88a0-c904857b24d7.png">

_____
V5 ([see full page](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418350319_Home_-__value_Prop_Highlight__V5))

**Comments:**
I like how value prop integrates with the "fresh" content on the right. It gives the feeling that the highlight is part of the value prop. The issue we may have with this proposal is when the highlight (content on the right) has a headline with 2 lines and lots of description. The hero space would look unbalanced. Also it can be a challenging layout for returning visitors on mobile since they will have to scroll a bit before seeing the "fresh" content.

**Screenshot:**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/22157921/82376741-6a614780-99d7-11ea-8ef1-e669797d604d.png">

@beccaklam @kristinashu could you please share some feedback with me in InVision? Once we choose a proposal I will add it to our main prototype. Thanks

**Comment by kristinashu** [comment] 2020-05-19 22:27
Thanks Tais! I like both v3 and v4. But if I had to chose I would lean towards v3 since the flow and structure is more straightforward. Perhaps we can mockup both versions once the copy is more final.

I think highlighting one current and accessible project is useful of new users as well as returning. It feels less overwhelming if there's a super clear CTA and seeing an example also helps to explain what we do.

**Comment by sabrinang** [comment] 2020-05-19 22:44
@taisdesouzalessa 
**V3** - The two grey lines segmenting this area in context feels a bit tight being so close to the nav line above as well (perhaps you do not need the grey line above, use small images instead or just none as options to open up this area a bit). 

**V4** - This is an interesting value prop sandwich where it frames fresh content with evergreen context above and below it. I do prefer the three column style in V3 over this four column (I don’t think you need that 'what we do and why it matters' blurb as the three should be self-explanatory?) but if it is really needed considering taking the title ‘what we do and why it matters’ above the three column. I also wonder if the project highlight is clear it is always changing since it comes right after the value prop and not describing more of the value prop itself (I think including a category/date/author byline could helps distinguish this is fresh content). If this whole section is considered together you may not need the top hr to be thick black but thin grey or none to lighten the visual weight in this area. 

**V5** - This feels text dense above the fold for some reason but I know it is the same amount (maybe the additional lines are feeling busy). Also, my eye is bouncing around quite a bit horizontally and wants to read the title value prop + image heading rows instead of columns on desktop (maybe because I am a returning user as well). 

+1 to consider mobile experience even though it is currently <30%

**Comment by taisdesouzalessa** [comment] 2020-05-20 03:40
Thanks for the feedback! I'll reiterate on the versions (plus add mobile) tomorrow.

**About the titles check (item number 2 of the ticket list)**:

I sent an email to the Content team asking for an async brainstorm - low pressure, only if they have the time and interest ([doc here](https://docs.google.com/document/d/1cRquctm-6CjI28Odh4y41osXMZpVuzjq538mhNTFlI0/edit?usp=sharing)). I will also add some ideas there and by Monday we will have the best ones placed on the wireframe.

**Comment by taisdesouzalessa** [comment] 2020-05-20 17:04
Here are 2 versions of this page, based on feedback received (I discarded V5 because it doesn't seem a good approach for the problem we are trying to solve):
• [V3 wireframe (desktop)](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418350320_Home_-_Value_Prop_Highlight_V3)
• [V3 wireframe (mobile)](https://mozilla.invisionapp.com/share/4MXDKYR2Q9C#/418497178_-M-_Home_-_Value_Prop___Highlight_V3)

• [V4b wireframe (desktop)](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418496658_Home_-__value_Prop_Highlight__V4b)
• [V4b wireframe (mobile)](https://mozilla.invisionapp.com/share/4MXDKYR2Q9C#/418497179_-M-_Home_-_Value_Prop___Highlight_V4b)

I added comments on InVision so we can discuss in the layout context.

cc: @kristinashu @beccaklam @sabrinang

**Comment by kristinashu** [comment] 2020-05-21 01:19
Sounds like V4 is the winner!

@taisdesouzalessa Anil has update the [homepage copy](https://docs.google.com/document/d/19Y5hNmEU4wix_gCoSvmhMKUk2F1Dht6Nwf1JQAu0lsg/edit#heading=h.jga10kqap7d8), could you please update the comp with it?

**Comment by taisdesouzalessa** [comment] 2020-05-21 19:39
After design critique I improved the wireframes and here is the latest version (with updated copy):

**Desktop:** [Wireframe here](https://mozilla.invisionapp.com/share/ZPWUGM6FKT2#/418693709_Home_-__value_Prop_Highlight__V4b_-_UPDATED_COPY)
**Mobile:** [Wireframe here](https://mozilla.invisionapp.com/share/4MXDKYR2Q9C#/418693824_-M-_Home_-__Home_-__value_Prop_Highlight__V4b_-_UPDATED_COPY)

I had to break down the copy in 2: I hope that is okay. 

I also updated the prototypes to reflect this new version of the home page.

cc: @kristinashu @beccaklam

**Comment by taisdesouzalessa** [comment] 2020-05-25 20:42
Jen, Audrey and I did a brainstorm on labels for this page. [Brainstorm documented here](https://docs.google.com/document/d/1cRquctm-6CjI28Odh4y41osXMZpVuzjq538mhNTFlI0/edit?usp=sharing). As we populate this page with real content we should also consider improving the labels with the suggestions by the team.

**Comment by taisdesouzalessa** [comment] 2020-05-25 20:43
Task completed! Closing this ticket.

**Closed by taisdesouzalessa** 2020-05-25 20:43 UTC
Labels: design
