### ISSUE TITLE
Show only month and year for publication date

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8807] opened 2022-05-25 19:22 UTC

**Comment by bheasman** [comment] 2022-07-18 11:05
@tbrlpld can we close this one? Looks like a dupe of #8808

**Comment by tbrlpld** [comment] 2022-07-18 13:02
@bheasman Sorry, must have been a fluke when creating these that it created two...

**Closed** 2022-07-18 13:02 UTC
