### ISSUE TITLE
Refactor wagtailpages/models.py into a folder

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#2362] opened 2018-12-18 20:55 UTC
We've got models defined in files outside of `wagtailpages/models.py` that we need to import manually (and add linter ignore flags) in order to get django to be "aware" of them. This isn't ideal, so lets create a folder `wagtailpages/models` and define models there, so django can pick them up automatically without the need for janky imports.

**Comment by cadecairos** [comment] 2019-03-07 15:51
@Pomax were you working on this issue again?

**Comment by Pomax** [comment] 2019-03-26 02:08
I was, and I think I should just sit down and finish it this week

**Comment by JoyLubega** [comment] 2019-06-01 19:36
Is there anyone working on this, if not can I be assigned this issue.

**Comment by harshs14** [comment] 2019-06-19 11:27
hi @Pomax, I am new here, can I take this up?

**Comment by Pomax** [comment] 2019-06-20 20:40
Ah, this work is already getting done by @youriwims, please have a look at the rest of the list of good first bug over on https://github.com/mozilla/foundation.mozilla.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by harshs14** [comment] 2019-06-21 05:56
@Pomax no problem, I will try to solve other issues, thanx

**Comment by Pomax** [comment] 2019-07-11 17:24
closing as duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/1801

**Closed by Pomax** 2019-07-11 17:24 UTC
Labels: Backend, enhancement, wagtail
