### ISSUE TITLE
Sliders on MozFest website do not have a constant height.

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#9905] opened 2023-01-06 14:29 UTC
### Describe the bug
Both iterations of slider blocks on the MozFest website have heights that are based on the content within each item in the slider. This leads to each item having differing heights so content jumps up and down on the page as the user changes the slider.

### To Reproduce
1. Go to 'https://www.mozillafestival.org'
2. Scroll down to 'Sustain the Momentum of MozFest'
3. You may need to reduce the window size until the text moves to a new line.

### Expected behavior
The height of all items within the slider should be same, and take the height from the largest item. Ideally each element within the items should align. (Eg: There is a multiline title on one item vs a single line title on another - this leads to the images and body content then not aligning.)

### Screenshots
![Screenshot 2023-01-06 at 14 24 12](https://user-images.githubusercontent.com/30226684/211031376-1e1b19f1-5ae7-483d-a8a7-b67cff2c5241.png)

**Comment by mtdenton** [comment] 2023-01-09 15:33
Hi Marc, we'll look to get this in during Sprint 1. @kristinashu, do you see any reason from a design perspective that we wouldn't want this to behave in the proposed way?

**Comment by kristinashu** [comment] 2023-01-09 16:36
Thanks for checking @mtdenton! Making them all the same height sounds like a good idea. @marcwalsh content-wise, I would still try to make each card have a similar amount of content and keeping the amount of content to a minimum, particularly for mobile.

**Comment by mtdenton** [comment] 2023-01-09 20:31
Thanks @kristinashu. With that, apparently this slider functionality is part of an external library that we didn't make, so @mmmavis is investigating what can be done here.

**Comment by mmmavis** [comment] 2023-01-10 00:41
@kristinashu I'm wondering if you prefer option 1 or option 2 (align buttons at bottom of the card)


### Option 1
https://user-images.githubusercontent.com/2896608/211435957-52aff08b-db0d-4bf4-bf57-489528d8e1ac.mov

### Option 2 (align buttons at bottom of the card)
https://user-images.githubusercontent.com/2896608/211435965-f2d61e0b-53c0-453e-8e8f-436c9881500f.mov

**Comment by kristinashu** [comment] 2023-01-10 01:20
@mmmavis thanks for showing the two examples. Option 1 is best since it is better at grouping the buttons with the content. The buttons feel a little lost in Option 2.

**Comment by mmmavis** [comment] 2023-01-11 00:11
Hello @marcwalsh, 

Happy new year! 
Changes are now on staging: https://mozillafestival.mofostaging.net/en/ Please let me know if this works good to you!

**Comment by marcwalsh** [comment] 2023-01-12 11:34
Happy New Year @mmmavis! :D 


This looks great until you get to a certain level of window size (tablet and below I think) - and the buttons start to overlap the bottom line.

Screenshot below:

<img width="752" alt="Screenshot 2023-01-12 at 11 24 57" src="https://user-images.githubusercontent.com/30226684/212055639-f902111e-c07d-4d77-bb77-d97da7ef2e17.png">

**Comment by marcwalsh** [comment] 2023-01-13 22:31
I noticed this on mobile also when loading the page the first time. I think it might be a major enough issue to fix before shipping given that's a first experience for some users.

**Comment by mtdenton** [comment] 2023-01-13 22:44
@marcwalsh which mobile device and browser are you using to see this issue? I've test a few actual device/browser combinations and I'm not seeing it.

**Comment by kristinashu** [comment] 2023-01-16 18:03
I'm seeing this as well on an iPhone 12 mini, iOS 16.1.2, in Safari 

![IMG_8014](https://user-images.githubusercontent.com/1068783/212741197-a255df84-a642-45ca-a3bd-0e4212ee3299.PNG)

![IMG_8013](https://user-images.githubusercontent.com/1068783/212741190-f6900371-2f1e-4b20-86cf-55b6fb6612cc.PNG)

**Comment by mmmavis** [comment] 2023-01-16 18:15
I'll revert the code changes from staging first. We are using a third-party library for the slider so there are limited customization we can do. I will try to find a solution.

**Comment by kristinashu** [comment] 2023-01-16 18:25
Good call to revert, thank you Mavis! @mmmavis do you have a link to the library that is being used (I'm curious what it looks like be default)? @marcwalsh how important is it do make the boxes the same size? I'm not sure it's worth overriding the library to make it happen.

**Comment by mmmavis** [comment] 2023-01-18 15:55
@kristinashu what's on the prod is using the library's default: https://www.mozillafestival.org/en/ 

I just tested my original fix again on iPhone 12 mini (emulator) and my own phone but I couldn't reproduce the issues above. I'm guessing sometimes image is loaded after the card's height has been calculated and set. That's why sometimes content ends up extending outside of the boundary? 

I have simple fix that seem to be working **for me**. If we wanna give it a try, I'll submit a PR and have it on staging for QA. It's this fix doesn't work again, we'll have to go on a more complex solution route (which will some JS/CSS overwrites).

**Comment by kristinashu** [comment] 2023-01-18 15:58
A simple fix sounds good and I can test it when it's ready!

**Comment by mmmavis** [comment] 2023-01-18 22:04
@kristinashu new fix is on staging now https://mozillafestival.mofostaging.net

**Comment by kristinashu** [comment] 2023-01-18 22:49
Nice, it looks right to me now!

**Comment by mmmavis** [comment] 2023-01-18 22:55
@kristinashu do you think this is okay to be pushed to prod today?

**Comment by mmmavis** [comment] 2023-01-18 23:07
I got the 🆗 via Slack!

**Comment by mmmavis** [comment] 2023-01-18 23:46
Closing. This looks good on production. Please let me know if otherwise. Thanks!

**Closed by mmmavis** 2023-01-18 23:46 UTC
Labels: engineering, mozfest 🎉

**Comment by marcwalsh** [comment] 2023-10-31 11:34
Hey @mtdenton @mmmavis - not sure if I should open a new ticket or reopen here, but I'm encountering the same/similar issue (not having a constant height) with the 'Session Sliders'.

**Comment by mtdenton** [comment] 2023-10-31 15:11
Hey @marcwalsh, happy to have a new ticket opened. Heads up we may not be able to get to this for a while since we're very slammed on end-of-year work.

Longer term, we need rethink our current implementation of this carousel library because it is not at all robust.
