### ISSUE TITLE
[QA Camaign pages] Page anchor goes too far down the page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1417] opened 2018-04-18 22:50 UTC
https://foundation.mozilla.org/wagtail/campaigns/aadhaar/take-action/#petition-form

When I click on the Take Action button it brings me too far down the page. It should take me to the top of the form but this is what I get:

<img width="1365" alt="screen shot 2018-04-18 at 3 48 09 pm" src="https://user-images.githubusercontent.com/1068783/38961997-112f195e-4320-11e8-8527-28c8264b144b.png">

**Comment by kristinashu** [comment] 2018-04-18 22:51
This seems to happen on the Mezzanine page too.

**Comment by Pomax** [comment] 2018-04-18 23:13
Yeah this is caused by our menu taking up "no space", so the page navigates to the correct spot, but we overlay the menu on it... Not sure what the right solution is there. @gvn, thoughs? "if URL contains #, add body.padding-top=100`? =D

**Comment by gvn** [comment] 2018-04-19 20:53
Yeah, this is a legacy issue. We'll probably need to do some kind of JS hackery to resolve it, but it's not a Wagtail thing.

**Comment by gvn** [comment] 2018-04-19 20:54
Dupe of #675

**Closed by gvn** 2018-04-19 20:54 UTC
Labels: quality test
