### ISSUE TITLE
Add banner indicating "draft" pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1055] opened 2018-02-13 22:00 UTC
We've got a lot of users logging in to the admin to view pages in progress. I'm concerned that they might forget that a page isn't published yet and try posting a link somewhere when it's ready. We should add a visible banner on the landing pages and campaign pages that show up if a page is in "draft" mode (and thus a user is logged in or else they wouldn't see the page).

It can simply be a banner across the top or bottom with a `#faf2cc` background that says 

"This page is currently a draft only visible by staff. Change it to 'published' in the admin page to make it public"

**Comment by alanmoo** [comment] 2018-02-13 22:16
@gvn Do any of the existing templates reference the draft/published status of the page?

**Comment by xmatthewx** [comment] 2018-02-14 15:57
related or duplicate of #984

**Closed** 2018-02-14 22:29 UTC
Labels: help wanted
