### ISSUE TITLE
CMS: page content shows up below nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2483] opened 2019-01-18 21:00 UTC
Noticing that two of the new draft mode pages is showing page content below the nav instead of to the right of it. @Pomax @mmmavis @alanmoo any idea why?

Example from doc:
<img width="1432" alt="screen shot 2019-01-18 at 12 55 44 pm" src="https://user-images.githubusercontent.com/1068783/51412548-bf115b80-1b20-11e9-997f-0a3bf07e55a0.png">

Example from campaign: 
<img width="1431" alt="screen shot 2019-01-18 at 12 57 16 pm" src="https://user-images.githubusercontent.com/1068783/51412549-bf115b80-1b20-11e9-9d51-1059665221ae.png">

**Comment by alanmoo** [comment] 2019-01-18 21:02
I've seen this bug before. I think it goes away when the page isn't in draft anymore, but I'm not sure what causes it.

**Comment by mmmavis** [comment] 2019-01-18 21:02
I'm guessing it's just some CSS issue (the main content is too wide to fit next to the nav). What's the URL to that page @kristinashu ?

**Comment by kristinashu** [comment] 2019-01-18 21:07
Ohhh just made this live https://foundation.mozilla.org/en/docs/brand/ and it's fixed!

**Comment by kristinashu** [comment] 2019-01-18 21:10
Here's the campaign one in draft mode and broken https://foundation.mozilla.org/cms/pages/263/view_draft/

**Comment by mmmavis** [comment] 2019-01-18 21:46
Might be related:
I checked out the source code of a draft opportunity parent page and found out the HTML code was invalid (extra/missing tags). Will have to investigate more to find out the root cause.

**Comment by mmmavis** [comment] 2019-01-21 21:02
https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/opportunity_page.html#L13-L24

```html
<div class="py-4 py-md-5
    {% if page.specific.narrowed_page_content and uses_menu %}
      col-md-7
    {% elif page.specific.narrowed_page_content %}
      offset-md-2
      col-md-8
    {% elif uses_menu %}
      col-md-9
    {% else %}
      col-md-12
    {% endif %}"
>
```

**Comment by mmmavis** [comment] 2019-01-21 21:04
https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/opportunity_page.html#L13-L24

```html
<div class="py-4 py-md-5
    {% if page.specific.narrowed_page_content and uses_menu %}
      col-md-7
    {% elif page.specific.narrowed_page_content %}
      offset-md-2
      col-md-8
    {% elif uses_menu %}
      col-md-9
    {% else %}
      col-md-12
    {% endif %}"
>
```

@alanmoo not sure how to fix this. I'm assuming properties we get from `page` is different when a page is in draft mode vs published mode?

**Comment by cadecairos** [comment] 2020-02-27 18:40
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.

**Closed by cadecairos** 2020-02-27 18:40 UTC
Labels: bug, engineering
