### ISSUE TITLE
Spotlight Section

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4841] opened 2020-07-02 18:07 UTC
![image](https://user-images.githubusercontent.com/177243/87202744-0449c000-c2b6-11ea-9b9d-a1a480d11de9.png)

**Comment by cadecairos** [comment] 2020-07-07 16:50
Q: What if a tag produces less than three items?

**Comment by Pomax** [comment] 2020-07-10 21:02
Fields:
- [ ] Feature image and heading (consider linking it)
- [ ] Staff choose 3 features
- [ ] Staff decide the order
- [ ] Design shows three ordered features, confirm if there should *always* be 3, no more no less.

**Comment by Pomax** [comment] 2020-07-10 21:04
@beccaklam would you know what to do in the situations that @cadecairos describes?

1. I assume we will never call out a tag/category that has fewer than 3 pages because we haven't done enough around work that yet =)
2. is this "any page that supports tags"?

**Comment by taisdesouzalessa** [comment] 2020-07-13 15:14
@Pomax I'll answer here since I am the assigned designer in my team to answer questions about this page :). @beccaklam feel free to contribute too if you wish/have the time!
1. That is correct: the goal of this section is to have curated content around a theme (e.g.: artificial intelligence, D&D, work by Fellows, work by Awardees) and I feel if the theme has less than 3 items it shouldn't belong this section. Please let me know if there is a scenario I am not considering.
2. The idea is to have a collection not only of categories (like D&D videos, work by Fellows) but also by themes (artificial intelligence or misinformation). I could see the theme "misinformation" having a Fellow project, a blog post by staff and an Awardee project, for instance - do you think we could make this work with tags? I think in this case the common tag would be "misinformation", right? 

A question I have is if the items can be chosen by staff (so not gathering the latest "misinformation" items, for instance but allowing people to choose the ones they want to display).

Happy to chat with you more about this section @Pomax if you want to talk in a call - we can brainstorm scenarios and solutions to make sure this section works as intended. Also, curious to hear your thoughts.

**Comment by mmmavis** [comment] 2020-07-27 23:24
@Pomax looks like this is done? I'm gonna close this ticket and start front end work. Please let me know if there's remaining backend work. 👍

**Closed by mmmavis** 2020-07-27 23:24 UTC
Labels: backend, engineering

**Comment by Pomax** [comment] 2020-07-27 23:30
interesting, yeah this should have auto-closed
