### ISSUE TITLE
[PNI] CTA box component [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9086] opened 2022-07-14 03:42 UTC
[Link to Figma component](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3231%3A33672)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/885100bc-a55d-4d52-b7e2-a73eccbf9032)

Create a wagtail component for the upcoming event promotion.

Dev Tasks:
* [ ] Title 
* [ ] Description
* [ ] Emoji PNG
* [ ] Apply Background gradient
* [ ] Link & Link text

Acceptance Criteria:

To be tested as part of  #9188

**Comment by cdanfon** [comment] 2022-07-25 17:37
Design is being updated, @beccaklam to update the ticket once design is complete and for @fessehaye to re-groom the ticket then,

**Comment by tbrlpld** [comment] 2022-08-04 16:07
Backend ticket: #9188

**Comment by tbrlpld** [comment] 2022-09-06 19:59
@fessehaye You mentioned in planning you might have some references for me regarding the gradient background. Would love to hear what you have 😄

**Comment by tbrlpld** [comment] 2022-09-08 21:34
@cdanfon I can not release this to the preview app because a bad PR was merged that breaks the PNI homepage (it's not pushed to the preview app yet).

**Comment by cdanfon** [comment] 2022-09-09 08:45
Thanks @tbrlpld 

Do we know when the next deployment is likely to happen?

**Comment by tbrlpld** [comment] 2022-09-09 12:23
@cdanfon That should happen after the issue is fixed. No idea when that will be worked on.

**Comment by cdanfon** [comment] 2022-09-09 16:14
Hey @tibor is this now unblocked based on this [convo](https://torchbox.slack.com/archives/CG07HH4G5/p1662726609164439?thread_ts=1662721872.105359&cid=CG07HH4G5)?

**Comment by tbrlpld** [comment] 2022-09-09 17:26
@cdanfon The frontend component can now be tested in the styleguide on the preview app: https://foundation-pni-2022.herokuapp.com/en/style-guide/#buyersguide

**Comment by cdanfon** [comment] 2022-09-12 12:24
Hey @tbrlpld thank you!

It looks good to me, the only thing to mention is that the Figma file has 2 variations of an icon: heart & eyes - see below:

<img width="960" alt="Screenshot 2022-09-12 at 13 22 45" src="https://user-images.githubusercontent.com/102978346/189652485-d8c214e6-3966-44c7-a8af-b43aa1490d01.png">

Is it worth including the eyes too? 
@beccaklam thoughts?

If the eyes are not necessary this ticket can be marked as complete :)

**Comment by tbrlpld** [comment] 2022-09-12 13:08
@cdanfon The image can be uploaded by the user in the backend. I don't think it makes sense to include this in the styleguide. If you want to test the eyes, you can upload a different image in the Wagtail admin for the styleguide

**Closed** 2022-09-12 13:29 UTC
Labels: engineering, blocked, Buyer's Guide 🛍, frontend, p2, Product
