### ISSUE TITLE
Investigate what to do with our wagtail_airtable integration for PNI

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7730] opened 2021-11-01 20:11 UTC
In order to allow data entry for the latest PNI iteration we had to disable Airtable integration for PNI products - we should look into whether we want to enable it again in the future, and what would be required to do so cleanly.

**Comment by KalobTaulien** [comment] 2021-11-24 16:51
It's a finicky package built on the notion of "what we have is what's in airtable" and if Airtable doesnt respond the save just fails.

It'd almost be better to create an Airtable action for a table that sends changed data to an endpoint on our side and create_or_update a page to reverse the work flow, and put Airtable first.

**Comment by Pomax** [comment] 2022-03-30 19:06
@kristinashu @anilkanji I suspect this will be more of an executive decision than a code decision, as using airtable for PNI is probably not an ideal solution to data entry streamlining

**Comment by kristinashu** [comment] 2022-03-30 19:20
Curious if @bheasman @tbrlpld have any insights into if it is possible to automate content entry for PNI? The research is complied in a [google spreadsheet](https://docs.google.com/spreadsheets/d/1LBEYx6DrYClG0pFkfwLdCZN3KzHRuMgMTjZBqPGD2sg/edit#gid=1764292170) but then everything has to be very manually entered into the CMS. Do you think there is a way to make this easier? 

Kalob had something that could import from Airtable but the stakeholder is pretty set on using google spreadsheets.

**Comment by tbrlpld** [comment] 2022-03-31 15:54
There is a package that's build around importing from Google spreadsheets. https://github.com/torchbox/wagtail-content-import

I have not used it, so I am not sure about the necessary development effort.

**Comment by tbrlpld** [comment] 2022-03-31 16:06
I was not able to find any existing packages for Spreadsheet import, but it should be possible. As I have not worked with the Sheets API, I can not yet speak to the efforts necessary. 

I am wondering how much work we would be ok with? E.g. much editor time is going to be saved by creating this functionality?

**Comment by tbrlpld** [comment] 2022-03-31 16:14
> as using airtable for PNI is probably not an ideal solution to data entry streamlining

@Pomax can you elaborate a bit on this? It that because this would be a second spreadsheet? What are the problems with the current implementation?

**Comment by kristinashu** [comment] 2022-03-31 21:10
The holiday edition of PNI had 150 products and I'd estimate it took about 6 minutes to enter each product, so the estimated time is very roughly 15 hours for content entry. Perhaps devs shouldn't spend more than that on it?

Some more background context: The stakeholder has always used Google Sheets for this work. Kalob already had a script for Airtable so the hope was that the stakeholder would use Airtable but it just doesn't work for them. But I am unsure of what the technical problem was with using Airtable.

**Comment by bheasman** [comment] 2022-04-01 08:26
Thanks @kristinashu. I wonder if the other consideration is importing [Google sheets to Airtable](https://support.airtable.com/hc/en-us/articles/360057784594-Google-Sheets-importer) and then allowing Airtable to be the source of truth for Wagtail. Has that been considered?

**Comment by jzinner** [comment] 2022-07-26 19:32
Product Manager, caltrider, confirmed that Airtable integration is not needed.
So closing this Issue - since the investigation phase is over and opening a new issue to remove the AIRTABLE integration from the repo. 
<img width="649" alt="Screen Shot 2022-07-18 at 2 23 11 PM" src="https://user-images.githubusercontent.com/7864372/181096079-faa70a3b-496a-4a19-8a5e-c1f44352c85e.png">

**Closed by jzinner** 2022-07-26 19:32 UTC
Labels: engineering, Buyer's Guide 🛍, backend
