### ISSUE TITLE
[PNI] - Create Campaign Page Type for PNI [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9103] opened 2022-07-14 19:57 UTC
The work for implementing the front end template for the buyers guide campaign page has been completed in #9082

**Comment by fessehaye** [comment] 2022-07-18 20:09
MVP: 
* Copy styling
* Low Priority at the moment

**Comment by tbrlpld** [comment] 2022-10-17 16:37
@nancyt1 @beccaklam Is this ticket still with design? The labels suggest it's an engineering ticket.

**Comment by kristinashu** [comment] 2022-10-18 16:03
@danielfmiranda it seems like you may have covered this in https://github.com/mozilla/foundation.mozilla.org/issues/9082, is that the case?

**Comment by mtdenton** [comment] 2022-10-21 22:00
@fessehaye @tbrlpld Need to eval if this is already done

**Comment by tbrlpld** [comment] 2022-10-25 15:53
This page seems to look ok, but should be checked by design: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/campaign-page-1/

**Comment by kristinashu** [comment] 2022-10-25 18:31
Thanks @tbrlpld! It is looking very close but I've noticed two things. Please let me know how best to document this.

- [ ] "All Reviews" is showing a selected state, it should show its non-selected state since it isn't selected.
- [ ] The image is slightly indented, it should be left aligned with the text like it is on all our other pages on the website.

Screen cap heroku link: 

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1068783/197852066-87c9d5e7-6d39-4063-8285-89426e6db320.png">


Screen cap of campaign page on our main site to show the left aligned image:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1068783/197853044-c41b3567-3ea6-4a97-8b75-9b4fe6cb835c.png">

**Comment by tbrlpld** [comment] 2022-10-25 21:35
@kristinashu I have updated the AC accordingly. Can you check this matches your understanding?

**Comment by kristinashu** [comment] 2022-10-25 22:52
Yes, looks good. I've also updated the Figma file and the screen caps (removed the newsletter signup CTA since that is post MVP and added an image as an example).

**Comment by danielfmiranda** [comment] 2022-12-09 00:28
Hi Everyone, since the title of this ticket is "Create the campaign page front end for PNI", and this work has technically already been completed in #9082, I am going to close this ticket and create a new one for the bugs found by design.

**Closed by danielfmiranda** 2022-12-09 00:28 UTC
Labels: engineering, Buyer's Guide 🛍, frontend, Product, p3

**Comment by danielfmiranda** [comment] 2022-12-09 00:34
I have removed this ticket from the sprint, and added ticket #9825 in its place!
