### ISSUE TITLE
Storytelling Wagtail Component: Looping Motion/Animation Hero

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#6678] opened 2021-05-11 06:08 UTC
### Intro
To allow for more compelling storytelling on the Wagtail blog pages, we want to implement subtle looping video animations within the hero block and full-width component areas. 

- Here's an example from the [Bill and Melinda Gates Foundation](https://www.gatesfoundation.org/) (💔)
- [Mozilla Festival](https://www.mozillafestival.org/en/) (although just the banner size) is another good example

***note***
Having Wagtail host this may not be possible—so if the option of [video embedding with a Vimeo Pro account](https://vimeo.zendesk.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos) is possible, that would be great!
---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized 
- [x] Link to original design ticket (original design ticket is in #831 (https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/831)
- [x] [Link to Redpen](https://redpen.io/p/wu5fe36cd1366a0cad)
- [x] [Link to Figma file](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=0%3A1)
- [x] Desktop, tablet, and mobile mockups are included
- [x] Assets are included. Link: (https://drive.google.com/open?id=15XTjgbU_UpnGBEGvslNe5AvX4kMGONM3&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
- [x] Hover state for elements are designed ([the prototype is here for the play/pause states on the page](https://www.figma.com/proto/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=55%3A766&scaling=min-zoom&page-id=55%3A700) and the designed [Figma file is here](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=55%3A700) for reference

- [ ] Copy looping video feature from MozFest homepage hero (make sure mobile behaviour is copied as well)
- [ ] Discuss with @KalobTaulien and/or @Pomax where to host videos (Vimeo or S3)
- [ ] Add a toggle to the blog page hero section config in the admin interface to allow toggling video on or off
- [ ] Add a field for the video URL

Please reach out to @natalieworth if you have any questions or need clarification! :)

**Comment by danielfmiranda** [comment] 2021-07-02 21:52
Closing as this appears to be a duplicate of #6675

**Closed by danielfmiranda** 2021-07-02 21:52 UTC
Labels: engineering
