### ISSUE TITLE
`Fixed blog page` cypress test is timing out

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#3833] opened 2019-11-01 10:48 UTC
**Describe the bug**
Percy tests are erroring because the test `Fixed blog page` is timing out.

Travis:
![Screenshot 2019-11-01 at 11 36 15](https://user-images.githubusercontent.com/481052/68019365-cebaf480-fc9b-11e9-96e2-7d235e624cb5.png)

Percy:
![Screenshot 2019-11-01 at 11 41 36](https://user-images.githubusercontent.com/481052/68019600-89e38d80-fc9c-11e9-8e11-d10919865c22.png)

@Pomax Can you take a look at what is happening there?
Meanwhile, I'm adding a skip to the broken test so that we can use Percy again.

**Comment by mmmavis** [comment] 2019-11-29 19:01
I'm assigning this to myself since it's related to a ticket ([add more visual regression tests](https://github.com/mozilla/foundation.mozilla.org/issues/2516)) I'm working on this sprint.

**Comment by mmmavis** [comment] 2019-11-29 19:40
@patjouk @Pomax 

Okay I've found the cause. It's related to video streamfield having issues when the embed url provided to it isn't valid.

- In `blog.py`, we config it so that fake blog post page contains a [video](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/factory/blog.py#L22) streamfield.
- But in `streamfiled_provider.py`, the [`url`](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/utility/faker/streamfield_provider.py#L111-L120) we used to create the fake video streamfield isn't a valid embed url... that's why it took Percy forever to wait for the embed video to load.

I've tested my theory in this [PR](https://github.com/mozilla/foundation.mozilla.org/pull/3982/files#diff-87b1cd73d0ffbb5b1080be01070b1a9bR116) by plugging in a real, working YouTube embed url... and Percy is no longer chocking on it](https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/3304069?utm_campaign=Mozilla-Foundation&utm_content=foundation.mozilla.org&utm_source=github_status_public).

I wonder if we should upload something to s3 and just use that as the video we use in video factory?

**Comment by Pomax** [comment] 2019-11-30 17:02
Hm, that's odd though, because cypress shouldn't care about whether an iframe loads or not, it should just take as screenshot no matter what the page looks like that that point. We might want to find out why it's refusing to (maybe we forgot a setting in Cypress that says "if you see a load error for anything, ignore that entire"?)

**Comment by mmmavis** [comment] 2019-12-05 00:05
Um I've spent quite a bit of time on this ticket but am now hitting a wall... I've also gone through Cypress and Percy docs but couldn't find anything relevant regarding iframe timeout.

I don't think I have the bandwidth to spend on this ticket this milestone anymore. If we want to enable Percy test for the blog post page, the quickest solution is to make sure blog post page doesn't include a video streamfield (which creates `<iframe>`) to avoid the bad embed url timeout issue. Or we can remove this ticket from this milestone and find time to figure out how we wanna deal with iframe loading for Cypress/Percy tests.

Thoughts? @alanmoo @Pomax

**Comment by Pomax** [comment] 2019-12-05 17:03
let's rip out the iframe, make the test work, and then have a ticket to put the iframe back in tied to a request for the percy folks to help us on this one using a normal support request on their side.

**Comment by Robdel12** [comment] 2019-12-05 17:54
Hey everyone! Percy support here. What @mmmavis is saying is correct:

> But in streamfiled_provider.py, the url we used to create the fake video streamfield isn't a valid embed url... that's why it took Percy forever to wait for the embed video to load.

> Hm, that's odd though, because cypress shouldn't care about whether an iframe loads or not, it should just take as screenshot no matter what the page looks like that that point. 

Percy isn't capturing _screenshots_ when the Cypress tests are running. We're capturing a DOM snapshot & then loading that DOM in a Puppeteer browser for "asset discovery". If the iframe doesn't have a valid src, this will cause both asset discovery and our rendering infrastructure to timeout. The timeout errors you're seeing in this screenshot is from Puppeteer failing to navigate to this DOM snapshot that was captured: 

![](https://user-images.githubusercontent.com/481052/68019365-cebaf480-fc9b-11e9-96e2-7d235e624cb5.png)

This is what it looks like when it fails to render in our browsers for a screenshot:

![](https://user-images.githubusercontent.com/481052/68019600-89e38d80-fc9c-11e9-8e11-d10919865c22.png)

> I wonder if we should upload something to s3 and just use that as the video we use in video factory?

This suggestion is spot on and I would highly recommend that approach. For build #3641, this is what the page looks like to us: 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/2072894/70260285-905e9c80-1755-11ea-9ef6-b08676ba2fa6.png">

The URL `https://robinson-sanchez.com/` is what is causing the issues here.

**Comment by Pomax** [comment] 2019-12-05 18:22
@cadecairos do we have a safe-but-generic video post on an S3 url that we can use as stable embed for testing?

**Comment by Pomax** [comment] 2019-12-05 18:35
Some alternatives we might also look at: 
- using an empty `href=""`, although I don't know if that makes the iframe "work" or whether that makes it a passive element until it gets an `href` set (like <img> with a missing `src`)
- using a data-uri or blob: url, with stubbed HTML content 
- using a `//:0` url

Those last two _might_ run into CSP limitations, but let's have a look.

**Comment by mmmavis** [comment] 2019-12-05 18:41
Thank you @Pomax and @Robdel12 for chiming in and providing help! ✨

**Comment by alanmoo** [comment] 2019-12-05 18:55
Maybe we should upload the creative commons trailer for this project like the video player I interned at years ago used: https://peach.blender.org/about/

**Comment by Pomax** [comment] 2019-12-05 19:00
honestly: we don't actually _care_ about what loads inside the iframe, just that it gets sized/placed correctly, so if we can update the test so that it doesn't even rely on the rest of the internet, that's probably better than uploading special pages somewhere.

But if we can't, CC for the win.

**Comment by mmmavis** [comment] 2019-12-05 20:25
Woohooo passing an empty string as embed url works! PR on the way!

**Comment by Robdel12** [comment] 2019-12-05 20:43
Anytime! Feel free to tag me in anything that comes up in the future too, I'd love to help 😃

**Comment by mmmavis** [comment] 2019-12-10 16:48
PR merged! Thanks all!

**Closed by mmmavis** 2019-12-10 16:48 UTC
Labels: engineering, testing
