### ISSUE TITLE
[PNI] Translating article categories & authors fails

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#9563] opened 2022-10-27 15:28 UTC
Attempting to translate a `Buyers guide article page author profile relation` or a `Buyers guide article page content category relation` from a PNI article page fails

How to reproduce:
- Translate a PNI article page
- Edit the translation
- Hit the translate button in front of `Buyers guide article page author profile relation` or `Buyers guide article page content category relation`

Example here:
https://foundation-pni-2022.herokuapp.com/cms/localize/submit/snippet/wagtailpages/buyersguidecontentcategory/1/

**Comment by tbrlpld** [comment] 2022-11-18 19:20
Sentry example error: https://sentry.io/organizations/mozilla/issues/3667651227/?environment=Staging&query=is%3Aunresolved&referrer=issue-stream

I was attempting to translate a profile. 

Here is the traceback:
```
Profile.DoesNotExist: Profile matching query does not exist.
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "wagtail_localize/views/submit_translations.py", line 242, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "wagtail_localize/views/submit_translations.py", line 190, in post
    return self.form_valid(form)
  File "contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "wagtail_localize/views/submit_translations.py", line 216, in form_valid
    single_translated_object = self.object.get_translation(
  File "wagtail/core/models/i18n.py", line 152, in get_translation
    return self.get_translations(inclusive=True).get(locale_id=pk(locale))
  File "django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
```

**Comment by tbrlpld** [comment] 2022-11-18 20:08
I am having trouble recreating this issue locally with fake date (`inv new-db`).

**Comment by tbrlpld** [comment] 2022-11-18 20:41
I can reproduce with staging data.

**Comment by tbrlpld** [comment] 2022-11-18 20:51
May be related: https://github.com/wagtail/wagtail-localize/issues/591

**Comment by tbrlpld** [comment] 2022-11-18 20:57
Ok, it works when I create a new profile in english locale, edit english page and create connection to the new profile, then sync the translations and publish the translated pages, then go to edit the translated page and click the translate button on the new profile. 

So there is some issue with existing data.

**Comment by tbrlpld** [comment] 2022-11-18 21:12
I think there might be an issue with existing profiles that don't have the "introduction" field populated.

**Comment by tbrlpld** [comment] 2022-11-18 21:22
PR #9029 makes this field required, as a request from @nancyt1. @danielfmiranda Has implemented that change. 

@nancyt1 @danielfmiranda Can you add some context why this change to the Profile model was necessary? Especially considering that the rendering is checking if the profile has an introduction. 

@TheoChevalier Is it acceptable as a workaround to add intros to the profiles that need translating?

**Comment by danielfmiranda** [comment] 2022-11-18 21:42
Hi @tbrlpld As far as I know, I don't believe the change was necessary but asked to be introduced as a way to promote that Authors add an introduction to their profile. 

But since the front end is not rendering any profiles without an introduction set, and there is also help text in the CMS letting users know that their profile will be hidden until there is an introduction, I think it is safe to make the field not required again. Unless design requests otherwise

**Comment by TheoChevalier** [comment] 2022-11-23 17:52
> PR #9029 makes this field required, as a request from @nancyt1. @danielfmiranda Has implemented that change.
> 
> @nancyt1 @danielfmiranda Can you add some context why this change to the Profile model was necessary? Especially considering that the rendering is checking if the profile has an introduction.
> 
> @TheoChevalier Is it acceptable as a workaround to add intros to the profiles that need translating?

Sorry for the delay — I think it’s totally fine yes, I also think (from the top of my head) that the intro line is currently the only one worth localizing, the other field being the author name itself?

**Comment by tbrlpld** [comment] 2022-11-23 21:54
I am creating a follow up ticket for the categories because it seems a bit more involved. 

#9757

**Comment by tbrlpld** [comment] 2022-11-24 01:11
@TheoChevalier I went a head and removed the introduction requirement anyhow, because of other potential side effects. 

Can you test that it works on staging?

(The categories still need to be dealt with, but that proved somehow more involved. I have created #9757 as a follow up.)

**Comment by cdanfon** [comment] 2022-11-24 17:37
@fessehaye please test this before pushing to prod

**Comment by fessehaye** [comment] 2022-11-24 18:53
Worked on staging for authors relations. I will move this for ready to prod

**Comment by fessehaye** [comment] 2022-11-24 20:19
On prod but leaving ticket open for @TheoChevalier  to check over

**Comment by TheoChevalier** [comment] 2022-11-25 09:12
Hey, here are my test results on staging:

- ✅ Adding an intro/tagline to an untranslated profile then translating it, works https://foundation.mofostaging.net/cms/snippets/wagtailpages/profile/edit/382/
- ❌ Adding an intro/tagline to an already translated profile, then syncing translations, fails https://foundation.mofostaging.net/cms/localize/update/606/?next=%2Fcms%2Fsnippets%2Fwagtailpages%2Fprofile%2F

**Comment by tbrlpld** [comment] 2022-11-28 15:44
@TheoChevalier This sounds a bit like a different use case. Would you mind creating a new ticket for that? 

This ticket is only meant to fix the issue with the authors described in the original ticket. Changing intro/taglines should not be necessary for testing this ticket.

**Comment by danielfmiranda** [comment] 2022-12-13 23:33
Pushed to prod! Closing

**Closed by danielfmiranda** 2022-12-13 23:33 UTC
Labels: bug 🦠, engineering, Buyer's Guide 🛍, localization 🌎, Product
