### ISSUE TITLE
Improve reader mode

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7196] opened 2021-08-09 16:07 UTC
I noticed that reader mode for https://foundation.mozilla.org/en/campaigns/regrets-reporter/findings/ only shows the Intro text and the end Recommendations but is missing most of the content.

- [ ] Update template so that it shows all the text in reader mode

Screen cap from prod:
![image](https://user-images.githubusercontent.com/1068783/128737079-c680bfe4-f387-4055-9295-8f84f32bfcb9.png)

**Comment by Pomax** [comment] 2021-08-09 16:46
To my understanding, all reader mode does is throw everything except <main> away, using "mostly its own CSS" that you get zero control over because if you did you could sneak all sorts of things back in with crafty before/after code (edited). Looking at the site in FF on desktop I get all the content when entering reader mode, which platform and browser does the content go missing for?

**Comment by kristinashu** [comment] 2021-08-09 16:52
I got this on my iPhone within Twitter (clicking on the link in Twitter opens the link within Twitter in Reader View). I don't really know how to test it more broadly.

**Comment by Pomax** [comment] 2021-08-09 20:43
I may have to hand this over to whomever has an iPhone =S

**Comment by kristinashu** [comment] 2021-08-10 22:12
@danielfmiranda let me know if I can help with anything!

**Comment by danielfmiranda** [comment] 2021-09-04 01:16
Hi Everyone! 

Here are my findings regarding this issue:

- I can confirm that for me as well, Firefox reader mode on both desktop and mobile render the content correctly.
- According to [this article](https://www.howtogeek.com/423643/how-to-use-google-chromes-hidden-reader-mode/), google chrome removed the reader view functionality in late 2019, and it is now only available through 3rd party extensions. However, the content also displayed correctly with them. 
- It appears that Safari is the only browser in which I can reproduce the bug in both mobile and desktop, and it appears that twitter is also using a safari based in-app browser, which is why it is not rendering correctly either.

After some more investigation, it appears that each browser implements its own algorithm for generating reader views ([link to mozillas](https://github.com/mozilla/readability)) If your page does not score high enough in this, the reader view button wont display at all. Which makes sense knowing that the content is rendering correctly on Firefox but not safari-based browsers. 

From what I have read and tested, it looks as if firefox reader mode is rendering any P element on the page, where Safari is instead looking for P elements that are grouped together under items like headings, etc.

Below is a screenshot of the youtube-regrets code with some extra elements that I have added outlined in red:
<img width="1182" alt="Screen Shot 2021-09-03 at 5 13 51 PM" src="https://user-images.githubusercontent.com/18314510/132077496-ab8b90bc-2d84-4792-993e-2f508b1aa66e.png">

Here it is rendered in Safari Reader Mode:
<img width="1182" alt="Screen Shot 2021-09-03 at 6 10 36 PM" src="https://user-images.githubusercontent.com/18314510/132077562-6636aab3-205f-4ed7-b489-2b02a8fb94d6.png">

We can see that the items #1 and #2 are being rendered, however the 3rd and 4th elements are being skipped, I am assuming since they are not wrapped in a outer div with other elements like headings and such. 

Taking a look at the youtube-regrets code, it seems like the items that are not being rendered are usually wrapped in multiple divs for bootstrap formatting, and then finally rendering a singular P tag.

My question for @benhohner @Pomax would be, should I create a follow up ticket for refactoring the code to work with safari reader mode? Or just wrap up this ticket?

Thanks! 

Links to items I read for those interested: 

- [How does fire fox reader mode operate](https://stackoverflow.com/questions/30661650/how-does-firefox-reader-view-operate/40747529#40747529)
- [Firefox reader mode source code](https://github.com/mozilla/readability)
- [Article about safari reader mode](https://medium.com/@mandy.michael/building-websites-for-safari-reader-mode-and-other-reading-apps-1562913c86c9)
- [More about safari reader mode](https://mathiasbynens.be/notes/safari-reader)

**Comment by kristinashu** [comment] 2021-09-16 16:39
Expanding the scope of this to include the Publications template since there has been feedback that users are having issues.

Table of contents on Publications pages and the navigation arrows at the bottom of Article pages are not visible in Twitter on my iPhone. 

Screen caps:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/1068783/133651497-b1148170-d6c5-4536-9225-8af3ed74ac2a.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1068783/133651535-c6347a45-8989-41cf-82ae-a12deb9aea6b.png">

**Comment by kristinashu** [comment] 2021-09-29 18:16
This is also the case with PNI product pages (can't see any info past the blurb). 

![IMG_7004](https://user-images.githubusercontent.com/1068783/135325783-bd2e2faf-bbcb-463b-b1ac-8b084f6aad0e.PNG)

**Comment by jamilasnell** [comment] 2021-11-22 21:29
@kristinashu doesn't seem like the solution for this issue would make sense for the audience size of this problem. I think we should close this issue as it would take a large amount of resources to solve.

**Comment by danielfmiranda** [comment] 2021-12-07 00:04
Spoke to Kristina and am closing the issue!

**Closed by danielfmiranda** 2021-12-07 00:04 UTC
Labels: design, engineering
