### ISSUE TITLE
Horizontal scroll behaviour on mobile: Initiatives Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4720] opened 2020-06-01 19:02 UTC
**Describe the bug**
Horizontal scroll activated on mobile version of "Initiatives" page: https://foundation.mozilla.org/en/initiatives/

**To Reproduce**
1. Either on your phone or using "responsive design mode" in your browser (Firefox) go to 'https://foundation.mozilla.org/en/initiatives/'
2. See horizontal scrolling

**Expected behavior**
No horizontal scrolling

**Screenshots**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/22157921/83443939-71d51780-a3ff-11ea-9d83-52f463d663d5.png">

**Comment by Pomax** [comment] 2020-06-02 16:46
going to close this as a duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/4586, and will bump that as an up next

**Closed** 2020-06-02 16:49 UTC
Labels: bug, engineering
