### ISSUE TITLE
Subpage titles are missing in title tag

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#2367] opened 2018-12-19 18:42 UTC
**Repro:** Go to any subpage and look at the title. It shows `Mozilla Foundation - `.
**Expected:** Add the subpage title after the hyphen.

<img width="584" alt="screen shot 2018-12-19 at 10 40 54 am" src="https://user-images.githubusercontent.com/206379/50240833-b808f900-037a-11e9-931a-45dafae23458.png">

**Comment by Pomax** [comment] 2019-01-29 01:01
Turns out this is still an issue - we should probably get that fixed sooner than later =)

**Comment by Dhrumilcse** [comment] 2019-01-31 06:51
I am getting started with Open Source and I'd like to work on this issue. Can I?

**Comment by Pomax** [comment] 2019-01-31 16:13
Hi @Dhrumilcse, absolutely - have you worked with Wagtail (or Django) and React before?

**Comment by Dhrumilcse** [comment] 2019-01-31 18:54
Thanks @Pomax, 
I am familiar with Django but I haven't worked with React before. However; I am ready to learn what's necessary. Also, I was looking through the code base and I think `<title>` section of base.html is where we need modifications. Correct me if I am wrong and guide me further.

**Comment by Pomax** [comment] 2019-01-31 21:02
That's correct, except each of the top level pages has their own template in https://github.com/mozilla/foundation.mozilla.org/tree/master/network-api/networkapi/wagtailpages/templates/wagtailpages/static that each needs to specify a new title.

If you look at https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html you can see that https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html#L15 already provisions a block called `pageTitle ` that is supposed to render "Mozilla Foundation - [...]" where the second part is generated from `page.meta_title` (`page` is a provided by wagtail as a context variable) and so the problem is that these pages either do not come with, or do not specify, that `meta_title` property.

**Comment by Dhrumilcse** [comment] 2019-02-01 08:17
Thanks @Pomax 
I got it and will work this out. Please assign me this issue.

**Comment by Pomax** [comment] 2019-02-04 18:42
I've added the label to "assigned to contributor", as only people who are part of the github org can be "assigned" to issues.

**Comment by Dhrumilcse** [comment] 2019-02-05 18:35
Hello team, I need guidance.

Because the foundation website contains a lot of modular code and Django's model-view-template pattern, it was a little difficult for me to reverse engineer it and find the solution. Therefore, I decided to create a small Django project and app on my local machine and run a case same as our issue. I found the solution on the local project. Here is my solution, briefly. **In the views.py file of the application, while defining the function for specific pages, we pass the 'template tag' with its definition (in our case, the subpage title) as an argument in the render function.** Please find the images containing code of the fix and the desired output.

So, once I got this, I went straight ahead to resolve the issue in the main project but couldn't find the file (views.py, I guess) to fix the issue. Can you tell me how should I fix this or if I am incorrect in any way, will you please guide me to the correct one?

[code]
![image1](https://user-images.githubusercontent.com/17984133/52295641-5d674300-29a2-11e9-9672-e5c2038044c0.png)

[output]
![image2](https://user-images.githubusercontent.com/17984133/52295648-60faca00-29a2-11e9-9156-198e70009695.png)

**Comment by xmatthewx** [comment] 2019-02-07 15:29
Ping @alanmoo @pomax

**Comment by alanmoo** [comment] 2019-02-07 15:47
It looks like this is working on Opportunity and Campaign pages, because the page editor gets to set the "title" property of the page on those templates.

Two relevant lines of code:
https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/templates/pages/base.html#L14

https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/models.py#L153-L154

It seems like the main thing we need is for unique page templates to set a title in their model, and the base template should pick it up.

**Closed** 2019-04-02 17:48 UTC
Labels: Frontend, assigned to contributor, bug, engineering, enhancement, good first issue
