### ISSUE TITLE
Move the PNI "about" pages into the wagtailpages/templates/buyersguide dir

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6477] opened 2021-04-01 16:36 UTC
Right now the PNI templates are located in `wagtailpages/templates/buyersguide` but the PNI about pages live in wagtailpages/templates/about` - these should live in wagtailpages/templates/buyersguide/about`, instead.

- [ ] move these pages
- [ ] update the code that links to these templates
- [ ] notify @TheoChevalier when this work gets done, so he can make sure those path changes are understood on the l10n side.

**Comment by TheoChevalier** [comment] 2021-04-07 17:51
@Pomax  Turns out it’s currently busted https://foundation.mozilla.org/fr/privacynotincluded/about/, I got fooled locally because I still had the old `locale` folders around, so it was using translations from these.

I removed the old folders, and now I can reproduce the issue locally. Then I had no clue why it was not using the files in `wagtailpages/templates/about/locale`.
`makemessages` is correctly extracting strings into them, `compilemessages` is processing them, but then for some reason Django don’t pick them at runtime.

Just found out the reason: the locale path is hardcoded here https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/settings.py#L433
We need `'networkapi/wagtailpages/templates/about/locale'`

**Comment by kristinashu** [comment] 2021-11-29 22:26
We would like to make all the About pages CMS editable https://github.com/mozilla/foundation.mozilla.org/issues/7958 - is this work blocking that?

**Comment by jamilasnell** [comment] 2021-12-20 19:34
> We would like to make all the About pages CMS editable #7958 - is this work blocking that?

This work is not blocking that! Closing this issue out per #8038!

**Closed by jamilasnell** 2021-12-20 19:34 UTC
Labels: engineering, wagtail, Buyer's Guide 🛍, backend, localization 🌎
