### ISSUE TITLE
[PNI] Mobile view is cut off - Black padding on the left hand side

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9490] opened 2022-10-14 09:54 UTC
### Describe the bug & steps to reproduce:

 [SCREEN RECORDING Homepage mobile view - PNI](https://vimeo.com/760235748/89e8acfff8)

### Expected behavior
Mobile view to fit screen and not to have black padding on right hand side.

### Additional context
See video.

**Comment by mtdenton** [comment] 2022-10-14 13:46
Funny this should come up, I started a conversation earlier this week with @kristinashu about support for very small screen sizes such as this. We concluded that 320px width should still be our minimum supported screen size in 2022/2023 based on our user data. Even though it constitutes less than 3% of traffic, we still want to ensure that these users have a good experience. As far as automated detection...

@tbrlpld @fessehaye @danielfmiranda, this particular issue seems testable across the entire site, I'd be interested in what implementation for a test would look like if we don't already have something (seems like we don't). Just spitballing, if scroll width of the outermost container is greater than client width of said container for any of the tested viewport sizes, that should probably raise some red flags.

I'll start a discussion elsewhere for now.

**Comment by cdanfon** [comment] 2022-10-14 15:43
Hey @mtdenton I've tested on iPhone 12 Pro (6.1" display) and the black line on the right-hand side is present too - see below. This only happens on the homepage of the preview app btw.
<img width="1035" alt="Screenshot 2022-10-14 at 16 40 43" src="https://user-images.githubusercontent.com/102978346/195887119-600584fc-dc39-49f1-ae83-27f39f5ddeec.png">

**Comment by tbrlpld** [comment] 2022-10-19 19:32
To me it just looks like that blub and the smiley at the top are just to wide and not responsvie.

**Comment by mtdenton** [comment] 2022-10-19 20:03
I'm wondering if we can do something like this to make this more responsive and provide a quick fix that doesn't look bad:

![twpni](https://user-images.githubusercontent.com/41487159/196792130-a0168dc2-2ccd-425f-b065-5e7c2d5270d2.JPG)

Sadly I can't get the breakpoint stuff for tailwind (md:xxxx or tw-md:xxxx) to work but I'm sure y'all have a better idea on how to get that done.

**Comment by tbrlpld** [comment] 2022-10-19 20:22
We could also allow the text to wrap and the smiley to shrink.

**Comment by kristinashu** [comment] 2022-10-19 20:38
Don't worry about the blurb and the smiley since it will soon be updated to just text.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/1068783/196799134-5689592e-817d-4281-a42d-abd2a4e2b829.png">

**Comment by mtdenton** [comment] 2022-10-19 21:37
Oh ok, gone completely then and no longer a thing forever. In that case, since this is P1 and we plan to get to it in this next sprint, I'm closing this as obsolete since it's the cause of the horizontal scroll.

**Closed by mtdenton** 2022-10-19 21:37 UTC
Labels: engineering, Product
