### ISSUE TITLE
signup component does not show customized "description" text

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3021] opened 2019-04-16 17:23 UTC
The signup component seems to not set the `description` text for the signup if one was explicitly specified in the signup snippet UI in the CMS.

Rather than replacing the default text with the custom-specified description, it seems to remove the default text (which would be correct) but not render the customized description (which is a bug).

**Comment by kristinashu** [comment] 2019-04-16 21:22
Oh this might not be a bug. I was able to add the copy. I think the issue is that both fields need to be filled in for it to show up
<img width="931" alt="image" src="https://user-images.githubusercontent.com/1068783/56244943-ffff0a80-6052-11e9-863f-371b20da2161.png">

**Comment by mmmavis** [comment] 2019-05-01 00:03
When I tested it last time (around 2 weeks ago), it seemed like the `[EN]` field was mandatory. So things worked as expected if you had `DESCRIPTION [EN]` filled. After you hit publish/save whatever the value was for `DESCRIPTION [EN]` would get auto copied to fill the `DESCRIPTION` field. 

Looks like the `DESCRIPTION` field is no longer there. Are we good to close this ticket?
<img width="853" alt="image" src="https://user-images.githubusercontent.com/2896608/57000736-c7d6ec00-6b69-11e9-93e7-e74af1661dbe.png">

**Comment by alanmoo** [comment] 2019-05-06 20:08
Looks like it.

**Closed by alanmoo** 2019-05-06 20:08 UTC
Labels: Backend, bug
