### ISSUE TITLE
Spike | Review Wagtail 3.0 upgrade

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8534] opened 2022-04-07 18:56 UTC
Goal of the spike: review upcoming Wagtail upgrade and highlight any potential risks/breakages/dependencies that we need to be aware of when making the upgrade

# Dev tasks 

- [x] Check changelog of the planned Wagtail 3.0 release (especially the "upgrade considerations") and check impact against out code.
- [x] Check out third-party dependencies and which are likely to break due to the Wagtail 3.0 upgrade. 
- [x] Create tickets for steps to prepare the codebase for the Wagtail 3.0 upgrade. 

# Acceptance criteria

- [x] We have an idea of how likely the Wagtail 3.0 upgrade is going to break the functionality of the site.
- [x] We have a list of our dependencies that are likely to break due to the Wagtail 3.0 upgrade.
- [x] If there are steps we can/have to take to prepare for the Wagtail 3.0 upgrade, tickets for these steps have been created.
- [x] We have a ticket for the Wagtail 3.0 upgrade. 
- [x] If we the Wagtail upgrade is blocked by other steps/tickets, the tickets have the respective dependencies in Zenhub.

**Comment by tbrlpld** [comment] 2022-10-14 23:37
@mtdenton @cdanfon 

I have had a look at this today. The changes in Wagtail itself seem easy to fix. The problem is we have 3 dependencies with unclear compatibility.

Here are some further notes:

- Upgrade considerations that will require changes — [https://docs.wagtail.org/en/stable/releases/3.0.html](https://docs.wagtail.org/en/stable/releases/3.0.html)
    - Changes to module paths.
        - Basically all imports to core wagtail modules need to be updated.
        - There is a management command provided to update all import paths.
    - Removal of special-purpose field panel types
        - All special field panels (like `RichTextFieldPanel` , `StreamFieldPanel`, etc.) can be replaced with the basic `FieldPanel`. The detection now happens automatically.
    - Use `use_json_field` argument for `StreamField`
        - All uses of `StreamField`should be updated to include the argument `use_json_field=True`.
    - Running the migrations might take a while, because of some restructuring internally. We will see this on staging, since staging has quite similar data as production.
- Check impact on third-party packages
    - Compatibility status of different packages (Analysis by Thibaud Colas) [https://docs.google.com/spreadsheets/d/1jNytHxjf4dMQwRaWqyIc2TT6VLN4RxQfBvnf5nseNSw/edit#gid=669425561](https://docs.google.com/spreadsheets/d/1jNytHxjf4dMQwRaWqyIc2TT6VLN4RxQfBvnf5nseNSw/edit#gid=669425561)
    - Compatible packages
        - wagtail-color-panel → yes
        - wagtail-localize==1.1 → yes
        - wagtail-factories  → yes
        - wagtailmedia → yes
        - wagtail-metadata → yes
    - Compatibility unclear
        - wagtail-airtable → unsure
        - wagtail-localize-git==0.12.0 → unsure
        - wagtail-inventory → unsure


I am unclear wether we still need these three dependencies. If we do, we could check test the compatibility by upgrading to Wagtail and see what is breaking. We could then report these issues and potentially contribute fixes.

**Comment by cdanfon** [comment] 2022-10-17 09:33
Hey @tbrlpld thanks for looking into this. 

In terms of the next steps how does the following look like this: 

1) Check if we still need these 3 dependencies

2) Prepare the codebase

     2.1) 
- Remove dependencies 

     2.2) 
- Changes to module paths 
- Removal of special-purpose field panel types
- Use use_json_field argument for StreamField

(if answer to 1) is negative we can skip step 2.1)

3)Test on staging

     3.1) Report and fix issues

4) Deploy to prod

@mtdenton I'm unsure who could action 1) - Could this be a you task?

**Comment by tbrlpld** [comment] 2022-10-18 16:29
@TheoChevalier Do we still use `wagtail-localize-git`?

**Comment by TheoChevalier** [comment] 2022-10-18 16:48
> @TheoChevalier Do we still use `wagtail-localize-git`?

Absolutely, it’s the piece of software that syncs content with the git repo used to exchange content with Pontoon: https://github.com/mozilla-l10n/fomo-content

We should be able to safely upgrade to 0.13, which is basically just a version bump to allow it running with the latest wagtail-localize releases

**Comment by cdanfon** [comment] 2022-10-19 08:34
I've updated my comment above to include a step to update wagtail localize-git to 0.13.0

**Comment by cdanfon** [comment] 2022-10-20 15:07
We just need to find out about wagtail-inventory now :)

**Comment by tbrlpld** [comment] 2022-10-31 16:44
Nobody is actively working on this, so I move this out of the sprint and back into to sprint ready.

**Comment by tbrlpld** [comment] 2022-11-11 16:57
Looks like `wagtail-inventory` is not a blocker anymore since it has been updated on supports Wagtail up to version 4.1 now: https://github.com/cfpb/wagtail-inventory/releases/tag/1.6

**Comment by cdanfon** [comment] 2022-11-11 17:05
Fantastic news thanks @tbrlpld 

So, I assume next steps are:

2.2) Changes to module paths | Removal of special-purpose field panel types | Use use_json_field argument for StreamField | Update wagtail-localize-git to 0.13.0

testing & deployment ?

**Comment by tbrlpld** [comment] 2022-11-11 17:34
@cdanfon I have created #9674 as the follow up ticket to this spike. 

Can you double check that the ACs are fulfilled? If so, I think we can close this spike.

**Comment by cdanfon** [comment] 2022-11-11 17:36
Yes Tibor! This makes me so happy! Almost there with Wagtail 3.0 👯

**Closed by cdanfon** 2022-11-11 17:36 UTC
Labels: engineering, Maintain
