### ISSUE TITLE
MozFest: subpage banner styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3207] opened 2019-05-22 01:44 UTC
@mmmavis can you please make the banner on all the mozfest sub pages look and resize the same as on the main sites Primary pages?

Desktop screen cap from main site:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1068783/58141196-626d9c80-7bf7-11e9-92fa-b05a481bbab9.png">

Desktop screen cap from mozfest: looks good except the font style is different
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1068783/58141233-8204c500-7bf7-11e9-85ed-d577fdaeb273.png">

Medium screen cap from main site:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/1068783/58141262-9b0d7600-7bf7-11e9-966e-ff8abf3eeec5.png">

Medium screen cap from mozfest: cut out and banner size is odd
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1068783/58141286-b11b3680-7bf7-11e9-98e5-93fad0808243.png">

Narrow screen cap from main site:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/1068783/58141303-c1331600-7bf7-11e9-86b0-37404a4956a5.png">

Narrow screen cap from mozfest: cut out is missing and banner size is odd
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1068783/58141318-cc864180-7bf7-11e9-8adf-e555922cf0b2.png">

cc @sabrinang

**Comment by Pomax** [comment] 2019-05-22 15:44
I'm pretty sure that visual discrepancy for the "about" page is because the banner graphic isn't higher than the desktop size, so the white space is caused by us not stretching out the banner image. We should be able to test this with a larger banner (that is to say, move vertical content).

**Comment by mmmavis** [comment] 2019-05-22 16:29
I can take a look after the homepage banner PR gets merged.

**Comment by kristinashu** [comment] 2019-05-22 16:54
Ah right @Pomax, I uploaded this banner with the correct dimensions and it crops much better now but the white cut out and the font still isn't exactly the same so yes, @mmmavis please take a look!

https://mozillafestival.mofoprod.net/en/about/

![sub-page-banner](https://user-images.githubusercontent.com/1068783/58193066-09dde400-7c77-11e9-87e5-e888e2d0ec67.jpg)

**Closed** 2019-05-23 16:24 UTC
Labels: Frontend
