### ISSUE TITLE
Full-Width Images

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#6874] opened 2021-06-16 21:26 UTC
### Describe the feature request
At the moment we have normal width images, which will follow the column count of the rest of the page, and then we have wide images which break out of that and move to col-12 to be a little bit wider than the rest of the pages content.

We would like to have images that span from one edge of the page to the other. After we update the templates to use the streamfields as rows method, this should be a matter of doing the following: 
- Add a flag to images for "full-width", similar to how we have a flag for "wide"
- Add some logic in the templates to properly display full width images. 

Here is an image showing an example: 
![image](https://user-images.githubusercontent.com/18314510/122296051-ce8e5d80-ceae-11eb-8654-932c68d98825.png)

**Comment by Pomax** [comment] 2021-06-21 20:50
closing as duplicate of https://github.com/mozilla/foundation.mozilla.org/issues/6676

**Closed by Pomax** 2021-06-21 20:50 UTC
Labels: backend, engineering, feature request, frontend
