### ISSUE TITLE
[PNI QA] CTA call out box is too big on Product Reviews page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9555] opened 2022-10-26 21:33 UTC
Currently the CTA call out box is too big on the Product Reviews page. You need to either go to the Product Reviews page directly or refresh the Product Reviews page if you came from another page (i.e. clicking 'Product Reviews' in the nav) in order to see this bug.

Currently:
![Screen Shot 2022-10-26 at 2.29.19 PM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/e5d4941e-3576-436c-aa21-e8bc9a91b899)

Should look like:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/18af0d20-8a32-4fc8-975c-9f7483d8780e)
[Link to design](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591)

## Acceptance criteria

- [x] As an editor, I can define a featured CTA in the Wagtail admin of the PNI homepage.
- [x] As a visitor, I do **not** see the featured CTA on the PNI homepage. 
- [x] As a visitor, I **do** see the featured CTA on the product reviews and category page embedded in the product grid.

**Comment by kristinashu** [comment] 2022-10-26 22:43
p3 with the assumption that this can be hidden

**Comment by tbrlpld** [comment] 2022-10-26 23:36
I presume it can by not defining a "featured CTA" on the PNI homepage.

**Comment by tbrlpld** [comment] 2022-11-30 18:23
Don't show CTA on the home page. Position correctly for the product reviews / category page.

**Comment by tbrlpld** [comment] 2022-12-14 22:56
The sizing was already taken care of in https://github.com/mozilla/foundation.mozilla.org/pull/9729. 

But, the switching logic does not yet work.

**Comment by tbrlpld** [comment] 2022-12-14 23:19
@beccaklam This should already be fixed through previous work. Can you double check that it looks as expected on staging? 

You will need to activate the display of the CTA on the category and load the category page with a full page refresh. 

I will create another ticket to deal with the switching of the categories.

**Comment by tbrlpld** [comment] 2022-12-14 23:32
Follow up for switching: #9853

**Comment by beccaklam** [comment] 2022-12-15 21:28
Hi @tbrlpld sorry for the late response. It seems like I do not have permission to create a CTA snippet. @mtdenton @kristinashu Do either of you know how I would get access?

**Comment by kristinashu** [comment] 2022-12-15 21:53
@tbrlpld which permissions role determines this? It looks like Becca has `administrate: PNI` so it seems like she should be able to but can't.

**Comment by tbrlpld** [comment] 2022-12-15 21:59
Interesting. I'll take a look.

**Comment by tbrlpld** [comment] 2022-12-15 22:01
@beccaklam Sorry, the group of PNI admins was missing the permission. It's fixed on staging now.

**Comment by tbrlpld** [comment] 2022-12-15 22:01
@beccaklam Sorry, the group of PNI admins was missing the permission. It's fixed on staging now.

**Comment by beccaklam** [comment] 2022-12-15 22:14
@tbrlpld Thank you for fixing the permissions! Kristina had already added a CTA so I used that for testing. We both noticed we see the CTA on the PNI homepage, article and product reviews pages, but not the Product Reviews (aka category page, sorry I know it's confusing) page?

**Comment by tbrlpld** [comment] 2022-12-15 22:16
@beccaklam Did you filter the product review page for a category and do a full page refresh? (the switching logic is not yet in place)

**Comment by tbrlpld** [comment] 2022-12-15 22:18
E.g. https://foundation.mofostaging.net/en/privacynotincluded/categories/entertainment/

**Comment by tbrlpld** [comment] 2022-12-15 22:19
Just noticing a different issue... the little icon is cropped... 

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/24797493/207979327-7724db67-f588-4bec-aee0-2916d247c71f.png">

I'll fix that

**Comment by beccaklam** [comment] 2022-12-15 22:37
@tbrlpld I guess I didn't do the full page refresh! The CTA is showing up for me now and looks good.

**Comment by beccaklam** [comment] 2022-12-15 22:39
Does this ticket cover hiding the CTA on the homepage?

**Comment by tbrlpld** [comment] 2022-12-15 23:54
No. The homepage editorial content needs to be hidden in general. Or repositioned. Are there tickets for that?

**Comment by tbrlpld** [comment] 2022-12-15 23:55
Oh... whooops.. looks like the AC cover the hiding on the homepage...

**Comment by tbrlpld** [comment] 2022-12-15 23:55
I'll go and fix that then.

**Comment by kristinashu** [comment] 2022-12-15 23:58
Thank you Tibor! Yeah, the quick fix was to hide it on the homepage and then the longer-term update is in https://github.com/mozilla/foundation.mozilla.org/issues/9758

**Comment by tbrlpld** [comment] 2023-01-10 01:48
This needed another followup PR...

**Comment by tbrlpld** [comment] 2023-01-10 16:28
@beccaklam This is now ready for testing on staging. 

1. Create a CTA (https://foundation.mofostaging.net/cms/snippets/wagtailpages/buyersguidecalltoaction/)
2. Set it as the featured CTA (https://foundation.mofostaging.net/cms/pages/1444/edit/)
3. Set a category to show the featured CTA (https://foundation.mofostaging.net/cms/snippets/wagtailpages/buyersguideproductcategory/edit/3/) 
4. Load the category page (https://foundation.mofostaging.net/en/privacynotincluded/categories/entertainment/)

**Comment by beccaklam** [comment] 2023-01-10 18:51
Hi @tbrlpld this is working for me, thank you for the very clear instructions. One question, when I click the homepage (https://foundation.mofostaging.net/en/privacynotincluded) and then navigate to the entertainment category by clicking the link (https://foundation.mofostaging.net/en/privacynotincluded/categories/entertainment/) the CTA does not load, and only appears when I refresh the page. Is there a reason for that and can we fix it? Or is that the expected behaviour?

**Comment by tbrlpld** [comment] 2023-01-10 19:13
Thanks for testing @beccaklam. 

Yes, for now this is intended behaviour, because the switching of the category is not aware of the CTA. @danielfmiranda will be working on #9853 that should implement the toggling of the CTA with JS when switching between categories using the category nav.

**Closed** 2023-01-11 00:12 UTC
Labels: bug 🦠, engineering, buyer's guide 🛍, product, p3
