### ISSUE TITLE
Automatically translated cms pages are missing content

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2863] opened 2019-03-20 21:27 UTC
I just went to https://foundation.mozilla.org/fr/ but noticed the body text for the hero is missing. I'm guessing this is happening on other pages as well and in other languages.

Issue on https://foundation.mozilla.org/fr/

<img width="1189" alt="Screen Shot 2019-03-20 at 2 20 56 PM" src="https://user-images.githubusercontent.com/1068783/54719977-76275480-4b1b-11e9-9e6f-714bf707163b.png">

How it should look https://foundation.mozilla.org/

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1068783/54720161-f8177d80-4b1b-11e9-83cf-b726a935eba7.png">

cc @mmmavis @alanmoo @Pomax

**Comment by mmmavis** [comment] 2019-03-20 21:51
It seems like rich text field content doesn't get auto copied when you switch language in CMS.

**Comment by alanmoo** [comment] 2019-03-21 14:40
Yeah. @Pomax Does this overlap with the other modeltranslation work?

**Comment by Pomax** [comment] 2019-03-26 21:27
hm, it a wagtail-specific version of modeltranslation, with both streamfield and richtextfield as extended types, so this _should_ have worked. I'll do some investigation here =(

**Comment by Pomax** [comment] 2019-03-27 18:48
So here's an interesting thing: if I set a value for the french text, publish, then remove that text again, and publish, so that in effect "nothing happened", the english text shows up just fine on the `/fr/` page so I'm wondering if somewhere along the line we ended up with things that "look empty, but technically aren't" for these fields.

**Comment by Pomax** [comment] 2019-03-27 18:52
Even if I just turn on the `[FR]` toggle in the cms, click the "write here" placeholder, _type nothing_, and then hit publish, this problem disappears... so at the very least we have a solution if there's nothing showing up in the code.

**Comment by Pomax** [comment] 2019-03-27 19:22
Looking at the database, it looks like all these fields are set to empty paragraphs:
```
foundation=# select * from wagtailpages_homepage
foundation-# ;
 page_ptr_id |        hero_headline         |                                                               hero_story_description                                                                | hero_button_text |                   hero_button_url                    | hero_image_id | search_image_id | hero_button_text_de | hero_button_text_en | hero_button_text_es | hero_button_text_fr | hero_button_text_pl | hero_button_text_pt | hero_button_url_de |                  hero_button_url_en                  | hero_button_url_es | hero_button_url_fr | hero_button_url_pl | hero_button_url_pt | hero_headline_de |       hero_headline_en       | hero_headline_es | hero_headline_fr | hero_headline_pl | hero_headline_pt | hero_story_description_de |                                                              hero_story_description_en                                                              | hero_story_description_es | hero_story_description_fr | hero_story_description_pl | hero_story_description_pt
-------------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+------------------+------------------------------------------------------+---------------+-----------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+--------------------+------------------------------------------------------+--------------------+--------------------+--------------------+--------------------+------------------+------------------------------+------------------+------------------+------------------+------------------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+---------------------------+---------------------------
          46 | Apply To Be a Mozilla Fellow | <p>WeÆre seeking technologists, activists, policy experts, and scientists devoted to a healthy internet. Apply to be a 2019-2020 Mozilla Fellow</p> | Apply today      | https://foundation.mozilla.org/en/fellowships/apply/ |           689 |             401 |                     | Apply today         |                     |                     |                     |                     |                    | https://foundation.mozilla.org/en/fellowships/apply/ |                    |                    |                    |                    |
       | Apply To Be a Mozilla Fellow |                  |                  |                  |                  | <p></p>                   | <p>WeÆre seeking technologists, activists, policy experts, and scientists devoted to a healthy internet. Apply to be a 2019-2020 Mozilla Fellow</p> | <p></p>
                 | <p></p>                   | <p></p>                   | <p></p>
```
which would throw off the model translation fallback... after doing the "place cursor, don't type, republish" trick, the data looks like:
```
foundation=# select * from wagtailpages_homepage;
 page_ptr_id |        hero_headline         |                                                               hero_story_description                                                                | hero_button_text |                   hero_button_url                    | hero_image_id | search_image_id | hero_button_text_de | hero_button_text_en | hero_button_text_es | hero_button_text_fr | hero_button_text_pl | hero_button_text_pt | hero_button_url_de |                  hero_button_url_en                  | hero_button_url_es | hero_button_url_fr | hero_button_url_pl | hero_button_url_pt | hero_headline_de |       hero_headline_en       | hero_headline_es | hero_headline_fr | hero_headline_pl | hero_headline_pt | hero_story_description_de |                                                              hero_story_description_en                                                              | hero_story_description_es | hero_story_description_fr | hero_story_description_pl | hero_story_description_pt
-------------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+------------------+------------------------------------------------------+---------------+-----------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+--------------------+------------------------------------------------------+--------------------+--------------------+--------------------+--------------------+------------------+------------------------------+------------------+------------------+------------------+------------------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+---------------------------+---------------------------
          46 | Apply To Be a Mozilla Fellow | <p>WeÆre seeking technologists, activists, policy experts, and scientists devoted to a healthy internet. Apply to be a 2019-2020 Mozilla Fellow</p> | Apply today      | https://foundation.mozilla.org/en/fellowships/apply/ |           689 |             401 |                     | Apply today         |                     |                     |                     |                     |                    | https://foundation.mozilla.org/en/fellowships/apply/ |                    |                    |                    |                    |
       | Apply To Be a Mozilla Fellow |                  |                  |                  |                  | <p></p>                   | <p>WeÆre seeking technologists, activists, policy experts, and scientists devoted to a healthy internet. Apply to be a 2019-2020 Mozilla Fellow</p> | <p></p>
                 |                           | <p></p>                   | <p></p>
(1 row)
```
It's not super obvious, but the `<p></p>` has disappeared for the French description.

**Comment by Pomax** [comment] 2019-03-27 19:35
@kristinashu @alanmoo this might actually be easiest for us to just manually fix by republishing pages than it would be to try to automate a fix, here. In which case the steps would be:
1. open the relevant page in the CMS,
2. enable all languages with the picker bar in the top right
3. for all "empty looking" rich text fields, put the cursor in, do a select-all+delete just to be sure, and then
4. republish the page

**Comment by kristinashu** [comment] 2019-03-28 21:12
Sorry, not sure I follow. Maybe we can chat after stand on Monday?

**Comment by Pomax** [comment] 2019-03-29 17:44
The code works exactly as intended, but the rich text fields that _look_ empty are not actually empty, they instead contain `<p></p>` making them only _look_ empty while containing data.

The most workable solution here is for us to find all the pages affected, open them in the CMS, and then manually make sure all the rich text fields for the "not-English" languages are cleared (even if they look empty already) and then republish those pages.

**Comment by alanmoo** [comment] 2019-03-29 18:01
Do we know how that happened though? It seems a bit unlikely empty content was pasted in.

**Comment by Pomax** [comment] 2019-04-02 17:04
I have no idea, and I don't even know how we would go about finding out.

**Comment by Pomax** [comment] 2019-07-09 21:18
hmm. @alanmoo @kristinashu I still don't know what the right course of action is here. As far as I can tell there is no way to determine _why_ this happened. I can update the database so that the problem is gone, but it'll be a bit of a manual job, as SQL isn't quite as easy as saying "for every column that ends in 'undercore letter leter', set the value to '' if the value is '<p></p>'" =(

**Comment by alanmoo** [comment] 2019-07-10 15:55
Do untouched (a page only created in English, with no attention paid to languages) rich text fields still get an empty paragraph tag, or does this seem to be a one-time occurrence?

**Comment by Pomax** [comment] 2019-07-10 16:41
they do not, they stay empty.

**Comment by alanmoo** [comment] 2019-07-10 18:22
![back-away](https://user-images.githubusercontent.com/1682681/60994197-0b926280-a31e-11e9-9b92-b8b21ff1b1b9.gif)
Maybe it was a one time thing with a weird migration/initial setup of translations? Since we can't replicate it, perhaps we should close it.

**Comment by Pomax** [comment] 2019-07-15 18:09
*poof*

**Closed by Pomax** 2019-07-15 18:09 UTC
Labels: bug
