### ISSUE TITLE
remove the ENABLE_PROFILE_DIRECTORY_BLOCK flag

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2721] opened 2019-02-25 16:38 UTC
all PRs for the directory component have now landed, so we can safely remove this feature flag from any of the code that relies on it, plus the settings file.

**Comment by youriwims** [comment] 2019-02-25 21:20
This is a dupe of #2706.

**Closed by youriwims** 2019-02-25 21:20 UTC
