### ISSUE TITLE
Unexpected Document and Image Collections names

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8293] opened 2022-02-22 23:30 UTC
When adding an image as well as a doc recently, I noticed the default category was very random sounding. Seems like it was perhaps carried over from our fake data? 

Low priority but it is mysterious! 

### To Reproduce
1. Go to https://foundation.mozilla.org/cms/images/
2. Click on 'All Collections1
3. See error the first two with bizarre names 

### Expected behavior
Only see normal (human generated) names

### Screenshots
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1068783/155237303-bb31e2ef-4c22-491b-8f37-0e71fe3f51a3.png">

**Comment by Pomax** [comment] 2022-03-30 19:33
Those look like test collections, and should never have ended up on production O_o

Let's find out what we can do to fix this @danielfmiranda @tbrlpld

**Comment by tbrlpld** [comment] 2022-12-20 00:30
It looks like this has happened before: #6720. 

It appears like someone accidentally ran some factory or test against the production database. The test documents that are part of one of these odd collections have a creation date of 2022-02-10 22:06 UTC. Around that time, there are 3 deployments. The first one failed because of missing migrations, then there are 2 more deployments that each run some unnamed data migrations. PR #8219 appears related. It is trying to fix some out-of-sync production data. 

My guess is that during that investigation the local environment was connected to the production database for inspection and that some tests or factory was run on accident while connected to it. I could not find any further details in the log archives. 

Luckily though, there is also the `clean_collections` script which has the exact functionality we need to fix this issue.

**Comment by cdanfon** [comment] 2023-02-06 19:24
**Tasks:** 

1. Get production data
2. Run clean collections
3. Report back

**Comment by danielfmiranda** [comment] 2023-02-10 01:04
After taking a look at this on my local machine, it appears that the `clean_collections` command would in fact solve this issue.


1. To test, I began by copying over the production data to my local machine by using the command `inv copy-prod-db`

2. Once the data was copied, I confirmed this by taking a look at the collection names. They are the same as in prod, including the unexpected ones:

<img width="1474" alt="Screenshot 2023-02-09 at 4 54 27 PM" src="https://user-images.githubusercontent.com/18314510/217973150-45546880-0202-454a-82aa-3fdcb04fa62b.png">


3. I then ran the `clean_collections` command which returned the following output (same as Tibors):
```
There are 2 duplicate root Collections
Working with Lawyer set other trade. Natural better several public area.
	Moving Screen Shot 2022-02-15 at 12.06.28 PM to the root collection
	Moving DSC_0019 to the root collection
	Moving mozilla-common-voice_foundation-banner3@2x to the root collection
	Moving mozilla-common-voice_foundation-6@2x to the root collection
	Moving YT-Regrets_MozillaYouTubeUCS_OG-Image-copy-(1) to the root collection
	Moving research-banner_01@2x to the root collection
	Moving icon_what-helps to the root collection
	Moving thumbnail-shifting-power to the root collection
	Moving thumbnail-IRL to the root collection
	Moving thumbnail-who-is-inovating to the root collection
	Moving thumbnail-what-could-go-wrong to the root collection
	Moving ou5A8Glngr8-MQ to the root collection
	Moving Blog Header - pni@2x to the root collection
...
	Deleting Lawyer set other trade. Natural better several public area.
Working with Name art word nation end. Pressure party story him.
	Deleting Name art word nation end. Pressure party story him.
```


4. After running this command, I then took another look at the collection names, and can confirm that the two unexpected ones have been removed, and only the expected collections remain:

<img width="1474" alt="Screenshot 2023-02-09 at 5 01 20 PM" src="https://user-images.githubusercontent.com/18314510/217973695-b00b94e4-22ff-4b8f-897d-5ab9ef2886a7.png">


5. Also, the number of pages for the "Latest Images" gallery has not been changed. There are 113 pages both before and after the command which is an indicator that no images have been deleted. However, I will run the python commands above to double check.

**Comment by danielfmiranda** [comment] 2023-02-10 19:38
I do also believe that this is safe to run in production to resolve this issue. Will coordinate with @tbrlpld next week to see when the best time to run this command would be

**Comment by tbrlpld** [comment] 2023-02-13 21:01
Sounds good to me @danielfmiranda

**Comment by tbrlpld** [comment] 2023-02-13 21:01
Maybe one thing to do before running this is production is to create a database backup, just in case.

**Comment by danielfmiranda** [comment] 2023-02-13 22:19
Sounds good @tbrlpld! 

I have ran the command `inv copy-prod-db` and it has saved a `.db.archive` file to my local machine with the prod data as of 02/13/23 at 2:15PM PST.

Are there any other ways you would like to backup the data before coordinating to run the `clean_collections` command?

**Comment by tbrlpld** [comment] 2023-02-13 22:25
I think there should be a button in Heroku or a way to do it with the Heroku CLI. I think that should be easier to restore than from a local file.  

https://devcenter.heroku.com/articles/heroku-postgres-backups

**Comment by danielfmiranda** [comment] 2023-02-13 22:26
Thanks Tibor! Going to take a look

**Comment by danielfmiranda** [comment] 2023-02-14 23:17
Going to put creating a backu + running this command on hold until after tomorrows 3.0 Wagtail push!

**Comment by danielfmiranda** [comment] 2023-02-18 00:32
After testing this out on my local machine with wagtail 3.0 and our previous version, as well as on staging. I can confirm that the `clean_collections`  command is working as intended for all versions. 

I am going to take advantage of the break in between deployments to run the command and close this ticket.

**Closed by danielfmiranda** 2023-02-18 00:32 UTC
Labels: bug 🦠, engineering, support
